?vault_statements: vault_connect
    | vault_disconnect
    | vault_default_ns
    | vault_create_ns
    | vault_read_ns
    | vault_update_ns
    | vault_delete_ns
    | vault_list_ns
    | vault_lock_ns
    | vault_unlock_ns
    | vault_create_mount
    | vault_read_mount
    | vault_update_mount
    | vault_delete_mount
    | vault_list_mounts
    | vault_create_kv_secret
    | vault_read_kv_secret
    | vault_read_kv_metadata
    | vault_update_kv_secret
    | vault_delete_kv_secret
    | vault_list_kv_secrets
    | vault_patch_kv_secret
    | vault_create_ldap_lib
    | vault_read_ldap_lib
    | vault_update_ldap_lib
    | vault_delete_ldap_lib
    | vault_list_ldap_libs
    | vault_create_ldap_secret
    | vault_read_ldap_secret
    | vault_update_ldap_secret
    | vault_delete_ldap_secret
    | vault_list_ldap_secrets
    | vault_rotate_ldap_secret
    | vault_api_get
    | vault_api_list
    | vault_api_delete
    | vault_api_post
    | vault_api_patch

// Connections
vault_connect   : "Vault"i {{Connect}} (_COMMA? vault_conn_arg)* _SEMICOLON?
vault_disconnect: "Vault"i {{Disconnect}} ("From"i? expr)? _SEMICOLON?
vault_conn_arg: "To"i "Host"i? expr -> conn_addr
    | ("With"i "Token"i? | "Token"i ("=" | "Is"i)) expr -> conn_token
    | "As"i expr -> conn_name

// Generic Vault API interactions
// The expr is the path part of the URL. It should include everything
//  except the host name and port. It may have to be URL encoded.
vault_api_get    : "Vault"i {{APIGet}} expr vault_args _SEMICOLON?
vault_api_list   : "Vault"i {{APIList}} expr vault_args _SEMICOLON?
vault_api_delete : "Vault"i {{APIDelete}} expr vault_args _SEMICOLON?
vault_api_post   : "Vault"i {{APIPost}} expr vault_args _SEMICOLON?
vault_api_patch  : "Vault"i {{APIPatch}} expr vault_args _SEMICOLON?

// Namespaces
vault_default_ns : "Vault"i {{DefaultNamespace}} expr _SEMICOLON?
vault_create_ns  : "Vault"i {{CreateNamespace}} expr vault_args _SEMICOLON?
vault_read_ns    : "Vault"i {{ReadNamespace}} expr vault_args _SEMICOLON?
vault_update_ns  : "Vault"i {{UpdateNamespace}} expr vault_args _SEMICOLON?
vault_delete_ns  : "Vault"i {{DeleteNamespace}} expr vault_args _SEMICOLON?
vault_list_ns    : "Vault"i {{ListNamespaces}} expr? vault_args _SEMICOLON?
vault_lock_ns    : "Vault"i {{LockNamespace}} expr vault_args _SEMICOLON?
vault_unlock_ns  : "Vault"i {{UnlockNamespace}} expr vault_args _SEMICOLON?

// Secret Engine Mount Points
vault_create_mount : "Vault"i {{CreateMount}} expr vault_args _SEMICOLON?
vault_read_mount   : "Vault"i {{ReadMount}} expr vault_args _SEMICOLON?
vault_update_mount : "Vault"i {{UpdateMount}} expr vault_args _SEMICOLON?
vault_delete_mount : "Vault"i {{DeleteMount}} expr vault_args _SEMICOLON?
vault_list_mounts  : "Vault"i {{ListMounts}} expr? vault_args _SEMICOLON?

// KV2 Secrets
vault_create_kv_secret : "Vault"i {{CreateKvSecret}} expr vault_args _SEMICOLON?
vault_read_kv_secret   : "Vault"i {{ReadKvSecret}} expr vault_args _SEMICOLON?
vault_read_kv_metadata : "Vault"i {{ReadKvMetadata}} expr vault_args _SEMICOLON?
vault_delete_kv_metadata : "Vault"i {{DeleteKvMetadata}} expr vault_args _SEMICOLON?
vault_update_kv_secret : "Vault"i {{UpdateKvSecret}} expr vault_args _SEMICOLON?
vault_delete_kv_secret : "Vault"i {{DeleteKvSecret}} expr vault_args _SEMICOLON?
vault_undelete_kv_secret : "Vault"i {{UndeleteKvSecret}} expr vault_args _SEMICOLON?
vault_destroy_kv_secret : "Vault"i {{DestroyKvSecret}} expr vault_args _SEMICOLON?
vault_list_kv_secrets  : "Vault"i {{ListKvSecrets}} expr vault_args _SEMICOLON?
vault_patch_kv_secret  : "Vault"i {{PatchKvSecret}} expr vault_args _SEMICOLON?

// LDAP Libraries Secrets
vault_create_ldap_lib : "Vault"i {{CreateLdapLibrary}} expr vault_args _SEMICOLON?
vault_read_ldap_lib   : "Vault"i {{ReadLdapLibrary}} expr vault_args _SEMICOLON?
vault_update_ldap_lib : "Vault"i {{UpdateLdapLibrary}} expr vault_args _SEMICOLON?
vault_delete_ldap_lib : "Vault"i {{DeleteLdapLibrary}} expr vault_args _SEMICOLON?
vault_list_ldap_libs  : "Vault"i {{ListLdapLibraries}} expr vault_args _SEMICOLON?

// LDAP Static Secrets
vault_create_ldap_secret : "Vault"i {{CreateLdapSecret}} expr vault_args _SEMICOLON?
vault_read_ldap_secret   : "Vault"i {{ReadLdapSecret}} expr vault_args _SEMICOLON?
vault_update_ldap_secret : "Vault"i {{UpdateLdapSecret}} expr vault_args _SEMICOLON?
vault_delete_ldap_secret : "Vault"i {{DeleteLdapSecret}} expr vault_args _SEMICOLON?
vault_list_ldap_secrets  : "Vault"i {{ListLdapSecrets}} expr vault_args _SEMICOLON?
vault_rotate_ldap_secret : "Vault"i {{RotateLdapSecret}} expr vault_args _SEMICOLON?

// Database Secrets Engine
vault_create_db_conn  : "Vault"i {{CreateDbConnection}} expr vault_args _SEMICOLON?
vault_read_db_conn    : "Vault"i {{ReadDbConnection}} expr vault_args _SEMICOLON?
vault_update_db_conn  : "Vault"i {{UpdateDbConnection}} expr vault_args _SEMICOLON?
vault_delete_db_conn  : "Vault"i {{DeleteDbConnection}} expr vault_args _SEMICOLON?
vault_list_db_conns   : "Vault"i {{ListDbConnections}} expr vault_args _SEMICOLON?
vault_reset_db_conn   : "Vault"i {{ResetDbConnection}} expr vault_args _SEMICOLON?
vault_rotate_db_conn  : "Vault"i {{RotateDbConnectionCredentials}} expr vault_args _SEMICOLON?

vault_create_db_role       : "Vault"i {{CreateDbRole}} expr vault_args _SEMICOLON?
vault_read_db_role         : "Vault"i {{ReadDbRole}} expr vault_args _SEMICOLON?
vault_update_db_role       : "Vault"i {{UpdateDbRole}} expr vault_args _SEMICOLON?
vault_list_db_roles        : "Vault"i {{ListDbRoles}} expr vault_args _SEMICOLON?
vault_generate_db_creds    : "Vault"i {{GenerateDbCredentials}} expr vault_args _SEMICOLON?
# Note: while other db_role calls use Type is dynamic/static,
#       rotate only applied to static. If you specify type, if must be static
vault_rotate_db_role_creds : "Vault"i {{RotateDbRoleCredentials}} expr vault_args _SEMICOLON?

# NB: Expression are treated like tokens iff they are a single name component
#     and are undefined in the data dictionary
vault_args: (_COMMA? vault_option (_COMMA? vault_option)*)?
vault_option: "CAS"i ("=" | "Is"i)? expr -> vopt_cas
    | "CAS"i "From"i var_name -> vopt_cas
    | "Config"i ("=" | "Is"i)? expr -> vopt_config
    | "Config"i "From"i var_name -> vopt_config
    | "Data"i ("=" | "Is"i)? expr -> vopt_data
    | "Data"i "From"i var_name -> vopt_data
    | "Description"i ("=" | "Is"i)? expr -> vopt_description
    | "Description"i "From"i var_name -> vopt_description
    | "Key"i ("=" | "Is"i)? expr -> vopt_key
    | "Key"i "From" var_name -> vopt_key
    | ("Meta"i | "Metadata"i) ("=" | "Is"i)? expr -> vopt_metadata
    | ("Meta"i | "Metadata"i) "From"i var_name -> vopt_metadata
    | "Namespace"i ("=" | "Is"i)? expr -> vopt_namespace
    | "Namespace"i "From"i var_name -> vopt_namespace
    | ("Result"i | "Results"i) ("=" | "Is"i | "In"i)? var_name -> vopt_result
    | "Giving"i var_name -> vopt_result
    | ("Secret"i | "Secrets"i) ("=" | "Is"i | "Are"i)? expr -> vopt_data # Alias for data
    | ("Secret"i | "Secrets"i) "From"i var_name -> vopt_data             # Alias for data
    | "Type"i ("=" | "Is"i)? expr -> vopt_type
    | "Type"i "From"i var_name -> vopt_type
    | "Using"i "Connection"i? expr -> vopt_using
    | ("Version"i | "Ver"i) ("=" | "Is"i)? expr -> vopt_version
    | ("Version"i | "Ver"i) "From"i var_name -> vopt_version
