?vault_statements: vault_connect
    | vault_disconnect
    | vault_default_ns
    | vault_create_ns
    | vault_read_ns
    | vault_update_ns
    | vault_delete_ns
    | vault_list_ns
    | vault_lock_ns
    | vault_unlock_ns
    | vault_create_mount
    | vault_read_mount
    | vault_update_mount
    | vault_delete_mount
    | vault_list_mounts
    | vault_create_kv
    | vault_read_kv
    | vault_update_kv
    | vault_delete_kv
    | vault_list_kvs
    | vault_create_ldap_lib
    | vault_read_ldap_lib
    | vault_update_ldap_lib
    | vault_delete_ldap_lib
    | vault_list_ldap_libs
    | vault_create_ldap_secret
    | vault_read_ldap_secret
    | vault_update_ldap_secret
    | vault_delete_ldap_secret
    | vault_list_ldap_secrets
    | vault_rotate_ldap_secret

// Connections
vault_connect   : "Vault"i "Connect"i (_COMMA? vault_conn_arg)* _SEMICOLON?
vault_disconnect: "Vault"i "Disconnect"i ("From"i? expr)? _SEMICOLON?
vault_conn_arg: "To"i "Host"i? expr -> conn_addr
    | ("With"i "Token"i? | "Token"i ("=" | "Is"i)) expr -> conn_token
    | "As"i expr -> conn_name

// Namespaces
vault_default_ns : "Vault"i ("DefaultNamespace"i | "default_namespace"i) expr _SEMICOLON?
vault_create_ns : "Vault"i ("CreateNamespace"i | "create_namespace"i) expr vault_args _SEMICOLON?
vault_read_ns   : "Vault"i ("ReadNamespace"i | "read_namespace"i) expr vault_args _SEMICOLON?
vault_update_ns : "Vault"i ("UpdateNamespace"i | "update_namespace"i) expr vault_args _SEMICOLON?
vault_delete_ns : "Vault"i ("DeleteNamespace"i | "delete_namespace"i) expr vault_args _SEMICOLON?
vault_list_ns   : "Vault"i ("ListNamespaces"i | "list_namespaces"i) expr? vault_args _SEMICOLON?
vault_lock_ns   : "Vault"i ("LockNamespace"i | "lock_namespace"i) expr vault_args _SEMICOLON?
vault_unlock_ns : "Vault"i ("UnlockNamespace"i | "unlock_namespace"i) expr vault_args _SEMICOLON?

// Secret Engine Mount Points
vault_create_mount : "Vault"i ("CreateMount"i | "create_mount"i) expr vault_args _SEMICOLON?
vault_read_mount   : "Vault"i ("ReadMount"i | "read_mount"i) expr vault_args _SEMICOLON?
vault_update_mount : "Vault"i ("UpdateMount"i | "update_mount"i) expr vault_args _SEMICOLON?
vault_delete_mount : "Vault"i ("DeleteMount"i | "delete_mount"i) expr vault_args _SEMICOLON?
vault_list_mounts  : "Vault"i ("ListMounts"i | "list_mounts"i) expr vault_args _SEMICOLON?

// KV2 Secrets
vault_create_kv : "Vault"i ("CreateKvSecret"i | "create_kv_secret"i) expr vault_args _SEMICOLON?
vault_read_kv   : "Vault"i ("ReadKvSecret"i | "read_kv_secret"i) expr vault_args _SEMICOLON?
vault_update_kv : "Vault"i ("UpdateKvSecret"i | "update_kv_secret"i) expr vault_args _SEMICOLON?
vault_delete_kv : "Vault"i ("DeleteKvSecret"i | "delete_kv_secret"i) expr vault_args _SEMICOLON?
vault_list_kvs  : "Vault"i ("ListKvSecrets"i | "list_kv_secrets"i) expr vault_args _SEMICOLON?

// LDAP Libraries Secrets
vault_create_ldap_lib : "Vault"i ("CreateLdapLibrary"i | "create_ldap_library"i) expr vault_args _SEMICOLON?
vault_read_ldap_lib   : "Vault"i ("ReadLdapLibrary"i | "read_ldap_library"i) expr vault_args _SEMICOLON?
vault_update_ldap_lib : "Vault"i ("UpdateLdapLibrary"i | "update_ldap_library"i) expr vault_args _SEMICOLON?
vault_delete_ldap_lib : "Vault"i ("DeleteLdapLibrary"i | "delete_ldap_library"i) expr vault_args _SEMICOLON?
vault_list_ldap_libs  : "Vault"i ("ListLdapLibraries"i | "list_ldap_libraries"i) expr vault_args _SEMICOLON?

// LDAP Static Secrets
vault_create_ldap_secret : "Vault"i ("CreateLdapSecret"i | "create_ldap_secret"i) expr vault_args _SEMICOLON?
vault_read_ldap_secret   : "Vault"i ("ReadLdapSecret"i | "read_ldap_secret"i) expr vault_args _SEMICOLON?
vault_update_ldap_secret : "Vault"i ("UpdateLdapSecret"i | "update_ldap_secret"i) expr vault_args _SEMICOLON?
vault_delete_ldap_secret : "Vault"i ("DeleteLdapSecret"i | "delete_ldap_secret"i) expr vault_args _SEMICOLON?
vault_list_ldap_secrets  : "Vault"i ("ListLdapSecrets"i | "list_ldap_secrets"i) expr vault_args _SEMICOLON?
vault_rotate_ldap_secret : "Vault"i ("RotateLdapSecret"i | "rotate_ldap_secret"i) expr vault_args _SEMICOLON?

vault_args: (_COMMA? vault_option (_COMMA? vault_option)*)?
vault_option: "Config"i ("=" | "Is"i)? expr -> vopt_config
    | "Data"i ("=" | "Is"i)? expr -> vopt_data
    | "Description"i ("=" | "Is"i)? expr -> vopt_description
    | "Key"i ("=" | "Is"i)? expr -> vopt_key
    | ("Meta"i | "Metadata"i) ("=" | "Is"i)? expr -> vopt_metadata
    | "Namespace"i ("=" | "Is"i)? expr -> vopt_namespace
    | "Result"i ("=" | "Is"i)? var_name -> vopt_result
    | "Type"i ("=" | "Is"i)? expr -> vopt_type
    | "Using"i "Connection"i? expr -> vopt_using
