?term_statements: term_statement

term_statement: ("Terminal"i | "Term"i) term_cmd (_COMMA? term_cmd)* _SEMICOLON?
?term_cmd: term_clear_cmd
        | term_cursor_cmd
        | term_opts_cmd
        | term_edit_cmd
        | term_misc_cmd
        | term_scroll_cmd
        | term_set_attr
        | term_draw_box

term_clear_cmd: ("ClearScreen"i | "Clear"i | "CLS"i) -> clear
        | "ClearEOL"i          -> clear_eol
        | "ClearEOS"i          -> clear_eos

term_cursor_cmd: ("CursorPos"i | "Pos"i | "cup"i) expr "," expr -> cup
        | ("Line"i | "vpa"i) expr? -> vpa
        | ("Col"i | "hpa"i) expr? -> hpa
        | ("CursorHome"i | "Home"i) -> cup_home
        | ("CursorSave"i | "CSave"i | "decsc"i) -> decsc
        | ("CursorRestore"i | "CRestore"i | "decrc"i ) -> decrc
        | ("CursorShow"i | "CShow"i) -> dectcem_set
        | ("CursorHide"i | "CHide"i) -> dectcem_reset
        | ("CursorVisible"i | "dectcem"i) ("=" expr)? -> dectcem
        | ("CursorUp"i | "cuu"i) expr? -> cuu
        | ("CursorDown"i | "cud"i) expr? -> cud
        | ("CursorLeft"i | "CursorBack"i | "cub"i) expr? -> cub
        | ("CursorRight"i | "CursorForward"i | "cuf"i) expr? -> cuf

term_edit_cmd: ("InsertLine"i | "InsertLines"i | "il"i) expr? -> il
        | ("DeleteLine"i | "DeleteLines"i | "dl"i) expr? -> dl
        | ("InsertChar"i | "InsertChars"i | "ich"i) expr? -> ich
        | ("DeleteChar"i | "DeleteChars"i | "dch"i) expr? -> dch
        | ("EraseChar"i | "EraseChars"i | "ech"i) expr? -> ech

term_scroll_cmd: ("ScrollUp"i | "ri"i) -> ri
        | ("ScrollDown"i | "ind"i) -> ind
        | ("ScrollRegion"i | "secstbm"i) expr "," expr -> secstbm

term_opts_cmd: "S7C1"i ("=" expr)? -> s7c1t
        | "S8C1"i ("=" expr)? -> s8c1t
        | "DECSCNM"i ("=" expr)? -> decscnm
        | ("SmoothScroll"i | "decsclm"i) ("=" expr)? -> decsclm
        | ("OriginMode"i | "decom"i) ("=" expr)? -> decom
        | ("AutoWrap"i | "decawm"i) ("=" expr)? -> decawm
        | ("InsertMode"i | "irm"i) ("=" expr)? -> irm

term_misc_cmd: ("Print"i | "p"i) expr -> print
        | ("DHPrint"i | "dhp"i) expr -> dh_print
        | ("SoftReset"i | "decstr"i) -> decstr
        | ("HardReset"i | "ris"i) -> ris
        | ("AlignmentTest"i | "decaln"i) -> decaln
        | ("TabSet"i | "hts"i) -> hts
        | ("TabClear"i | "tbc"i) -> tbc
        | ("TabClearAll"i | "tbc_all"i) -> tbc_all
        | ("RepeatChar"i | "rep"i) expr? -> rep
        | "DeIconify"i -> deiconify
        | "RaiseWindow"i -> raise_window
        | "IconName"i expr -> icon_name
        | "WindowTitle"i expr -> window_title
        | "NUL"i -> ctrl_nul
        | "SOH"i -> ctrl_soh
        | "STX"i -> ctrl_stx
        | "ETX"i -> ctrl_etx
        | "EOT"i -> ctrl_eot
        | "ENQ"i -> ctrl_enq
        | "ACK"i -> ctrl_ack
        | "BEL"i -> ctrl_bel
        | "BS"i  -> ctrl_bs
        | "HT"i  -> ctrl_ht
        | "LF"i  -> ctrl_lf
        | "VT"i  -> ctrl_vt
        | "FF"i  -> ctrl_ff
        | "CR"i  -> ctrl_cr
        | "SO"i  -> ctrl_so
        | "SI"i  -> ctrl_si
        | "DLE"i -> ctrl_dle
        | "DC1"i -> ctrl_dc1
        | "DC2"i -> ctrl_dc2
        | "DC3"i -> ctrl_dc3
        | "DC4"i -> ctrl_dc4
        | "NAK"i -> ctrl_nak
        | "SYN"i -> ctrl_syn
        | "ETB"i -> ctrl_etb
        | "CAN"i -> ctrl_can
        | "EM"i  -> ctrl_em
        | "SUB"i -> ctrl_sub
        | "ESC"i -> ctrl_esc
        | "FS"i  -> ctrl_fs
        | "GS"i  -> ctrl_gs
        | "RS"i  -> ctrl_rs
        | "US"i  -> ctrl_us

term_set_attr: "Reset"i -> sgr_reset
        | "Bold"i ("=" expr)? -> sgr_bold
        | "Dim"i ("=" expr)? -> sgr_dim
        | "Blink"i ("=" expr)? -> sgr_blink
        | ("Italic"i | "Italics"i) ("=" expr)? -> sgr_italic
        | ("Underline"i | "UL"i) ("=" expr)? -> sgr_underline
        | ("Foreground"i | "FG"i) ("=" expr)? -> sgr_fg
        | ("Background"i | "BG"i) ("=" expr)? -> sgr_bg
        | ("Reverse"i | "Rev"i) ("=" expr)? -> sgr_reverse
        | ("Hidden"i | "Hide"i) ("=" expr)? -> sgr_hidden
        | ("Strikethrough"i | "Strikethru"i | "Strikeout"i ) ("=" expr)?  -> sgr_strikethru
        | ("Double"i | "decdwl"i) ("=" expr)? -> decdwl
        | ("Single"i | "decswl"i) ("=" expr)? -> decswl
        | ("HighTop"i | "decdhl_top"i) ("=" expr)? -> decdhl_top
        | ("HighBottom"i | "HighBot"i | "decdhl_bot"i) ("=" expr)? -> decdhl_bot

term_draw_box: ("DrawBox"i | "Box"i) expr "," expr ("," expr)? -> box
             | ("DrawHLine"i | "DrawLine"i | "HLine"i) expr ("," expr)?  -> hline
             | ("DrawVLine"i | "VLine"i) expr ("," expr)? -> vline
