[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vgr"
version = "1.1.7"
description = "VGR - A scripting language"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE.txt" }
authors = [{ name = "Ross Virostko", email = "ross.virostko@citizensbank.com" }]
dependencies = [
    "Jinja2>=3.1.6",
    "lark>=1.2.2",
    "ldap3>=2.9.1",
    "prompt_toolkit>=3.0.50",
    "RapidFuzz>=3.13.0",
    "rich>=13.9.4",
    "blessed>1.23.0; sys_platform == 'win32'"
]

[project.scripts]
vgr = "vgr.vgr:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0"
]
extras = [
    "pyperclip>=1.11.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"vgr" = ["*.ini", "*.ebnf", "**/*.ebnf", "**/*.ini", "**/*.json"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-v"
testpaths = ["tests"]
pythonpath = ["."]
