[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vgr"
version = "1.1.11"
description = "VGR - A Scripting Language"
readme = "README.md"
requires-python = ">=3.9"
license = "LicenseRef-Hippocratic-HL3"
license-files = ["LICENSE.md"]
authors = [
    { name = "Ross Virostko", email = "ross.virostko@citizensbank.com" },
    { name = "Ross Virostko", email = "rvirostko@icloud.com" },
]
dependencies = [
    "blessed>1.23.0; sys_platform == 'win32'",
    "httpx[http2]>=0.28.1",
    "Jinja2>=3.1.6",
    "lark>=1.2.2",
    "ldap3>=2.9.1",
    "prompt_toolkit>=3.0.50",
    "pwinput>=1.0.3",
    "python-hcl2>=7.3.1",
    "PyYAML>=6.0.3",
    "RapidFuzz>=3.13.0",
    "rich>=13.9.4"
]
keywords = ["etl", "data", "parsing", "automation", "vault", "reporting"]
# PyPI classifiers
classifiers = [
    "Development Status :: 4 - Beta",

    # Audience
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",

    # Topics
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security",
    "Topic :: Software Development :: Interpreters",
    "Topic :: System :: Networking",
    "Topic :: System :: Systems Administration",
    "Topic :: Text Processing :: Filters",
    "Topic :: Utilities",

    # Python versions
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    # Environment
    "Environment :: Console",
    "Operating System :: OS Independent",
]

# Project URLs (shown in PyPI, accessible via metadata)
[project.urls]
Homepage = "https://github.com/rvirostko/vgr"
#Documentation = "https://vgr.readthedocs.io"
Repository = "https://github.com/rvirostko/vgr"
#Issues = "https://github.com/yourusername/vgr/issues"
#Changelog = "https://github.com/yourusername/vgr/blob/main/CHANGELOG.md"

[project.scripts]
vgr = "vgr.vgr:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
    "pytest-cov"
]
extras = [
    "pyperclip>=1.11.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"vgr" = ["*.ini", "*.lark", "**/*.lark", "**/*.ini", "**/*.json"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-v"
testpaths = ["tests"]
pythonpath = ["."]
