#! /usr/bin/env python3

from typing import Any
import argparse
import os
import sys
import traceback
import logging

from lark import Lark

from app_exceptions import VgrExitingException, VgrException
from data_dict import DataDictionary
from dd_config import dd_init, dd_parse_user_args
from doc_help import print_md, search_entries, is_probably, print_doc, unique_by_func
from extn import VgrExtensionRegistry, VER
from functions import get_function_defs, add_builtin_functions, add_function, get_function_entries, get_operator_entries
from interactive import CmdLine, ArgumentParser, ParserBuilder
from log_config import init_logging, set_logging_level
from mathpak import poly_bool, type_str
from output import expand_filename
from redir import print_stderr
from exec_context import ExecContext
from stmt_exec import (
    create_exec_context,
    get_statement_entries,
    STATEMENT_HANDLERS,
)

# Autogenerated: maintained by bump_version.sh
from version import __version__, __version_date__, __description__

LOG = logging.getLogger()

class VGRCmdLine(CmdLine):
    _DEFAULT_HISTORY = '~/.vgr_history'
    _DEFAULT_PROMPT = 'vgr> '

    _SOURCE_PARSER: ArgumentParser = (ParserBuilder()
                    .argument('file', type=str)
                    .parser())

    def __init__(self, ctx: ExecContext):
        assert ctx
        self._ctx = ctx
        self._prompt = self._get_vgr_default('prompt', self._DEFAULT_PROMPT)
        self._history_filename = self._get_vgr_default('history', self._DEFAULT_HISTORY)
        self._max_history_entries = self._get_vgr_default('history_size', CmdLine._DEFAULT_HISTORY_SIZE)
        super().__init__()

    def run(self):
        print_md('_Type `exit` to exit_')
        return super().run()

    def execute_statements(self, text: str) -> bool:
        try:
            self._ctx.execute_statements(text.rstrip(), '<repl>')
        except VgrException as e:
            # The only exit interactive mode "honors" is the actual exit request
            # With assertions, fatal errors, et al, we just continue
            if isinstance(e, VgrExitingException):
                t: VgrExitingException = e
                if t.statement.data == 'exit':
                    return False
            if self._ctx.debug:
                traceback.print_exc(file=sys.stderr)
            else:
                print(str(e))
        except Exception as e: # pylint: disable=broad-exception-caught
            if self._ctx.debug:
                traceback.print_exc(file=sys.stderr)
            else:
                print(str(VgrException(None, e, None, None)))
        return True

    def print_verbose(self, *args, **kwargs) -> None:
        self._ctx.print_verbose(*args, **kwargs)

    def print_exception(self, e: Exception) -> None:
        if self._ctx.verbose:
            print(e, file=sys.stderr)
        else:
            print(e.args[0] if e.args else f'{type_str(e)}', file=sys.stderr)

    def _get_vgr_default(self, env_var: str, default: Any) -> str:
        """Look for a matching environment variable (uppercase) and return it or the default value"""
        return os.getenv('VGR_' + env_var.upper(), default)

# TODO we can start to carve up the READ-ME into parts to add to
# language topics.
    def _exec_help(self, *args) -> None:
        """
**Language Topics**

* `function` : Search functions only for help
* `operator` : Search operators only for help
* `statement` : Search statements only for help

If no value provided with `function`, `operator`, or `statement` search, a list
the associated items is displayed.

`help` used with any other value searches through
language features looking for an exact match.

For example `help Add` with return informtion for the `Add()` while
`help statement Add` is required to get information for the like-named statement.

**REPL Topics**

* `cd` : Change the current working directory
* `history` : Display or control command line history
* `multiline` : Turn on multiline editing mode
* `prompt` : Define the input input prompt
* `pwd` : Print the current working directory
* `shell` : Work with the OS sub-shell
* `version` : Display version information

"""
        if len(args) < 1:
            print_doc(self._exec_help)
        else:
            topic = args[0]
            targs = args[1:]
            q = (' '.join(targs) if targs else '').strip()
            if is_probably("version", topic) or topic in ("ver", "v"):
                print()
                print_md(f'**{__version__} {__version_date__}**')
                print()
            elif is_probably("cd", topic):
                print_doc(self._exec_cd)
            elif is_probably("help", topic) or is_probably("topics", topic) or topic in ("?", "/h", "/?"):
                print_doc(self._exec_help)
            elif is_probably("pwd", topic) :
                print_doc(self._exec_pwd)
            elif is_probably("history", topic):
                print_doc(self._exec_history)
            elif is_probably("multiline", topic):
                print_doc(self._exec_multiline)
            elif is_probably("prompt", topic):
                print_doc(self._exec_prompt)
            elif is_probably("shell", topic):
                print_doc(self._exec_subshell)
            elif is_probably("function", topic):
                results = self._get_function_help(q) if q else self._all_help(get_function_entries())
                self._display_function_help(q, results)
            elif is_probably("operator", topic) or topic in ("ops", "op"):
                results = self._get_operator_help(q) if q else self._all_help(get_operator_entries())
                self._display_operator_help(q, results)
            elif is_probably("statement", topic) or is_probably("stmt", topic):
                results = self._get_statement_help(q) if q else self._all_help(get_statement_entries())
                self._display_statement_help(q, results)
            else:
                # If no explicit topic that matches, then see what we can find
                # in statements, functions, and operators
                q = topic + ' ' + q
                func_help = self._get_function_help(q)
                if len(func_help) == 1:
                    self._display_function_help(q, func_help)
                else:
                    op_help = self._get_operator_help(q)
                    if len(op_help) == 1:
                        self._display_operator_help(q, op_help)
                    else:
                        stmt_help = self._get_statement_help(q)
                        if stmt_help:
                            self._display_statement_help(q, stmt_help)
                        else:
                            print()
                            print_md('_Use **help topics** to list topics_')
                            print()

    def _all_help(self, entries: list) -> list:
        return unique_by_func([(name, entries[name][0]) for name in sorted(entries.keys())])

    def _get_operator_help(self, q) -> list:
        return search_entries(get_operator_entries(), q)

    def _get_statement_help(self, q) -> list:
        return search_entries(get_statement_entries(), q)

    def _get_function_help(self, q) -> list:
        return search_entries(get_function_entries(), q)

    def _display_operator_help(self, q, results) -> None:
        results = [(func.bound_ops[0], func) for _name, func in results]
        self._display_help_results("Operators", q, results)

    def _display_statement_help(self, q, results) -> None:
        self._display_help_results("Statements", q, results)

    def _display_function_help(self, q, results) -> None:
        results = [(name + "()", func) for name, func in results]
        self._display_help_results("Functions", q, results)

    def _display_help_results(self, search_type: str, q: str, results: list) -> None:
        if len(results) == 0:
            # We could not find anything
            print()
            print_md(f'_Nothing matches{" " + repr(q) if q else ""}_')
            print()
        elif len(results) == 1:
            # We got an single match
            # Show the help for the item
            print_doc(results[0][1])
        else:
            # Multiple results
            # Show as a list with a summary
            lines = []
            lines.append(f'**{"Search Results" if q else search_type}-**')
            for name, func in results:
                doc = (func.__doc__ or "").strip()
                if doc:
                    # Display first non-blank line, stripped of bolding (the convention) and no sentence
                    lines.append(f'* `{name}` - {doc.splitlines()[0].strip().strip("*").rstrip(".")}')
                else:
                    lines.append(f'* `{name}`')
            print()
            print_md('\n'.join(lines))
            print()

def load_extensions(dd: DataDictionary, extn_file: str, debug: bool, verbose: bool) -> VgrExtensionRegistry:
    if verbose: print_stderr('Loading extensions...')
    print_debug(debug, 'Extension file is', extn_file)
    VER.load(dd, extn_file)
    extns=[]
    for extn_name, extn in VER:
        extns.append((extn_name, f'{extn.__class__.__module__}.{extn.__class__.__qualname__}',extn.adds_statements(), extn.extends_select(), ))
        if extn.adds_statements():
            for name, handler in extn.statement_handlers().items():
                if name in STATEMENT_HANDLERS:
                    raise ValueError(f'Extension {extn_name!r} tried to redefine {name!r}')
                STATEMENT_HANDLERS[name] = handler
        for func_name, func in extn.functions().items():
            add_function(extn_name, func_name, func)
    dd.set_var(extns, *('vgr', 'extensions'))
    return VER

def create_parser(grammar_file: str, extn_registry: VgrExtensionRegistry, debug: bool, verbose: bool) -> Lark:
    if verbose: print_stderr('Creating parser...')
    extn_from = ''
    extn_statements = ''
    extn_grammar = ''
    for name, instance in extn_registry:
        # By convention, if an extension says it has statements or extends the From clause
        # it should have a like named rule in its grammar
        if instance.extends_select(): extn_from += f' | {name}_from'
        if instance.adds_statements(): extn_statements += f'| {name}_statements'
        extn_grammar += instance.grammar()
        if not extn_grammar.endswith('/n'): extn_grammar += '\n'
    print_debug(debug, 'EXTN_STATMENTS =', extn_statements)
    print_debug(debug, 'EXTN_FROM =', extn_from)
    print_debug(debug, 'EXTN_GRAMMAR =', extn_grammar)
    print_debug(debug, 'Grammar file is', grammar_file)
    with open(grammar_file, 'r', encoding='utf-8-sig') as file:
        grammar = file.read()
    # NB: we can't just use str.format() because the grammar
    #     contains "{" and "}"
    for tag, value in (('{EXTN_STATEMENTS}', extn_statements),
                       ('{EXTN_FROM}', extn_from),
                       ('{EXTN_GRAMMAR}', extn_grammar),
                       ('{FUNCTIONS}', get_function_defs())):
        grammar = grammar.replace(tag, value)
    print_debug(debug, 'GRAMMAR =\n', grammar)
    return Lark(grammar,
                start=['opt_statements', 'expr'],
                lexer='contextual',
                parser='lalr',
                debug=True,
                propagate_positions=True,
                cache=True)

class SaveOrderedSources(argparse.Action):
    def __call__(self, *args, **_):
        # unpack here rather than in signature to appease pylint
        _, namespace, values, option = args
        if not hasattr(namespace, "ordered"):
            namespace.ordered = []
        namespace.ordered.append((option.lstrip('-')[0].lower(), values))

def print_debug(debug: bool, /, *args, **kwargs) -> None:
    """If debug is on print to stderr and maybe the log"""
    if debug:
        print_stderr(*args, **kwargs)
        if LOG.isEnabledFor(logging.DEBUG):
            LOG.debug(*args, **kwargs)

def print_exc(ctx: ExecContext) -> None:
    print("!!")
    #if ctx.debug:
    traceback.print_exc(file=sys.stderr)

def main():
    clp = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=f'Version {__version__} ({__version_date__})',
        epilog="""Statements added with --execute and --file are executed in the order they are given.

Following that, statements are read from stdin if they are available.

If no --execute and --file arguments are given, and stdin is interactive, by default the REPL is started. Using --repl false prevents it from opening.

Additional arguments are added to the "arg" variable. Only simple data types can be set. Quotes are not required for strings.

--verbose, --debug, and --echo control only the initial settings. Commands in --execute and --file arguments can still change them when running.

Environment variables:
  - OFS/ORS - output field and record separators as defined by AWK
  - VGR_PROMPT - REPL prompt; limited Bash-like escapes supported
  - VGR_HISTORY - path to REPL's history file
  - VGR_HISTORY_SIZE - max number of lines stored in history
"""
    )
    clp.add_argument('-v', '--version', action='version', version=f'{__version__} {__version_date__}')
    clp.add_argument('-e', '--execute', nargs='*', metavar='STATEMENTS', action=SaveOrderedSources,
                    help='Execute the given statements')
    clp.add_argument('-f', '--file', nargs='*', metavar='FILE', action=SaveOrderedSources,
                     help="Execute statements stored in a file")
    clp.add_argument('--verbose', metavar='BOOL', type=poly_bool,
                    help='Enable/disable verbose mode')
    clp.add_argument('--debug', metavar='BOOL', type=poly_bool,
                    help='Enable/disable debug mode')
    clp.add_argument('--echo', metavar='BOOL', type=poly_bool,
                    help='Enable/disable statement echo')
    clp.add_argument('--repl', metavar='BOOL', type=poly_bool,
                    help='Request/prohibit the REPL. REPL automatically starts if --execute/--file are not used')
    clp.add_argument('--logfile', type=str, default=None,
                    help='Path to the log file')
    clp.add_argument('--loglevel', type=str, default='info',
                    help='Logging level (debug, info, warning, error, critical)')
    clp.add_argument('--logoverwrite', action='store_true',
                    help='Overwrite log file instead of appending')
    clp.add_argument('user_args', nargs='*', metavar='NAME=VALUE',
                    default=[], help='Additional arguments. Values maybe booleans, numbers, or strings')
    args = clp.parse_args()

    init_logging(args.logfile, args.logoverwrite)
    set_logging_level(args.loglevel)
    LOG.info('Starting')
    # Since it's startup, and everything else relies on the DD...
    if args.verbose: print('Creating data dictionary...', file=sys.stderr)
    dd = DataDictionary()
    dd_init(dd)
    add_builtin_functions() # Done prior to loading extensions to prevent them overwriting
    extensions = load_extensions(dd,
                                 os.path.join(os.path.dirname(os.path.abspath(__file__)), 'extensions.ini'),
                                 args.debug, args.verbose)
    parser = create_parser(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'vgr.ebnf'),
                           extensions,
                           args.debug, args.verbose)
    ctx = create_exec_context(parser, dd)
    ctx.debug = args.debug
    ctx.verbose = args.verbose
    ctx.echo = args.echo
    if args.user_args:
        ctx.print_verbose('Parsing user args...')
        dd_parse_user_args(dd, args.user_args)

    LOG.info('Ready')

    # NB: args.execute and args.file will always be None
    #     as there values have been accumulated in
    #     args.ordered so they can be handled in the order
    #     received. Additionally, each option can be
    #     an ordered list.
    exit_code: int = VgrExitingException.EXIT_SUCCESS
    try:
        ordered_args = args.ordered if hasattr(args, "ordered") else []
        # Accumulated -e/-f options, stored in the order given
        for opt in ordered_args:
            stype, svalue = opt
            if stype == 'e':
                # Simple statements directly on the command line
                for statements in svalue:
                    ctx.print_verbose('Executing statements from command line...')
                    ctx.execute_statements(statements, '<cmd-line>')
                continue
            if stype == 'f':
                # Statements stored in a file
                for filename in svalue:
                    # NB: we don't "sandbox" these files like we do with others
                    filepath = expand_filename(filename)
                    ctx.print_verbose('Executing statements from ', repr(filepath), '...')
                    statements = None
                    with open(filepath, 'r', encoding='utf-8-sig') as f:
                        statements = f.read()
                    ctx.execute_statements(statements, filename)
                continue
            raise NotImplementedError(f'Statement source {stype!r} not implemented') # SNO
        if sys.stdin.isatty():
            # "--repl" forces opening a REPL
            # "--repl false" prevents opening it
            # when not given, we look to having previously executed -e/f commands
            if args.repl is True or (args.repl is None and not ordered_args):
                ctx.print_verbose('Starting the REPL...')
                VGRCmdLine(ctx).run()
                ctx.print_verbose('REPL exited')
        else:
            # Read from stdin, most likely from a "here" document
            # but can be from a pipe or just a "<"
            ctx.print_verbose('Executing statements from stdin...')
            ctx.execute_statements(sys.stdin.read(), '<stdin>')
    except VgrExitingException as e:
        exit_code = e.exit_code
    except VgrException as e:
        LOG.exception('Exception')
        print_exc(ctx)
        print_stderr(str(e))
        print_debug(ctx.debug, e)
        exit_code = VgrExitingException.EXIT_FAILED
    except Exception as e: # pylint: disable=broad-exception-caught
        # Last resort catch: log it and exit
        LOG.exception('Exception')
        print_exc(ctx)
        print_stderr(str(VgrException(None, e, None, None)))
        print_debug(ctx.debug, e)
        exit_code = VgrExitingException.EXIT_FAILED
    ctx.print_verbose(f'Exit code is {exit_code}')
    LOG.info('Exiting')
    sys.exit(exit_code)

if __name__ == '__main__':
    main()
