// Omitted from the parse tree
_DOT: "."
_COMMA: ","
_LPAREN: "("
_RPAREN: ")"
_SEMICOLON: ";"
_OSB: "["
_CSB: "]"

// Converted to their literal values after parsing
TRUE.90: "true"i
FALSE.90: "false"i
NONE.90: "none"i | "null"i
INF.90: "inf"i
NAN.90: "nan"i

// Numeric values
// NB: octal and binary regexs are shorter than the length
//     of the decimal regex, so we need to boost their
//     priorities so the former's leading zero doesn't get
//     prematurely matched by the latter.
HEX_NUMBER.2: /0[xX](_?[0-9a-fA-F])+/
OCT_NUMBER.2: /0[oO](_?[0-7])+/
BIN_NUMBER.2: /0[bB](_?[01])+/
DEC_NUMBER: /-?[0-9](_?[0-9])*/
_SPECIAL_DEC: /[0-9](_?[0-9])*/
_EXP_PART: /[eE][+-][0-9](_?[0-9])*/
// NB: slight difference from Python as floats can't end with a "."
_DECIMAL: _DOT _SPECIAL_DEC | _SPECIAL_DEC _DOT _SPECIAL_DEC
FLOAT_NUMBER: "-"? (_SPECIAL_DEC _EXP_PART | _DECIMAL _EXP_PART?)

// "snake case", "kabab case", and mixed version of the two
// For "kabab", it cannot start with a hyphen and an alpha character must follow a hyphen
// This is an attempt to prevent some subtraction operations from looking like identifiers
NAME: /[A-Za-z_]([A-Za-z0-9_]|-+[A-Za-z])*/

statements: statement+
?statement: simple_statement
    | select
    | control_statements
    {EXTN_STATEMENTS}

?simple_statement: assert
    | break
    | close
    | continue
    | debug
    | echo
    | exit
    | load_from
    | open
    | pass
    | print
    | printf
    | set
    | sleep
    | sort
    | unset
    | verbose
    | zip

?control_statements: if_statement
    | unless_statement
    | while_statement
    | until_statement
    | foreach_statement
    | repeat_statement

if_statement: "If"i expr ("Then"i | "Do"i | ":") statement+ else_clause? "End"i _SEMICOLON? -> if
unless_statement: "Unless"i expr ("Do"i | ":") statement+ "End"i _SEMICOLON? -> unless
while_statement: "While"i expr ("Do"i | ":") statement+ "End"i _SEMICOLON? -> while
until_statement: "Until"i expr ("Do"i | ":") statement+ "End"i _SEMICOLON? -> until
repeat_statement: "Repeat"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> repeat
foreach_statement: "ForEach"i var_name "In"i expr ("Do"i | ":") statement+ "End"i _SEMICOLON? -> foreach
else_clause: "Else"i ("Do"i | ":") statement+ -> else
break: "Break"i _SEMICOLON?
continue: "Continue"i _SEMICOLON?

// simple boolean on/off, true/false
// these are "proper statements" as they control the behavior of other statements
debug: "Debug"i _SEMICOLON
    | "Debug"i ("=" | "Is"i)? expr _SEMICOLON?
echo: "Echo"i  _SEMICOLON
    | "Echo"i ("=" | "Is"i)? expr _SEMICOLON?
verbose: "Verbose"i _SEMICOLON
    | "Verbose"i ("=" | "Is"i)? expr _SEMICOLON?

pass: ("Pass"i | "Nop"i) _SEMICOLON?

sleep: "Sleep"i "For"i? expr ("Seconds"i | "Second"i)? _SEMICOLON?

set: "Set"i var_name ("=" | "To"i) expr _SEMICOLON?
    | "Var"i? var_name ("=" | "Is"i) expr _SEMICOLON?
    | ("Set"i | "Var"i)? var_name IN_PLACE_OP expr _SEMICOLON? -> set_in_place
IN_PLACE_OP: ("+=" | "-=" | "*=" | "/=" | "//=" | "%=" | "**=" | "&=" | "|=" | "^=" | "<<=" | ">>=" )

unset: "Unset"i var_name (_COMMA? var_name)* _SEMICOLON?

load_from: "Load"i var_name ("From"i | "With"i) "File"i? expr ("As"i? load_source_type)? _SEMICOLON?
load_source_type: "JSON"i "Object"i? -> json_object
    | "JSON"i "Object"i? "Per"i "Line"i -> json_objects
    | "CSV"i -> csv_file
    | "TEXT"i -> text_file

assert: "Assert"i _SEMICOLON
    | "Assert"i expr (":" expr (_COMMA expr)*)? _SEMICOLON?

print: "Print"i _SEMICOLON
    | "Print"i expr (_COMMA expr)* _SEMICOLON?

printf: "Printf"i _SEMICOLON
    | "Printf"i expr (_COMMA expr)* _SEMICOLON?

open: "Open"i io_type "File"i? expr open_ext? _SEMICOLON?
close: "Close"i io_type "File"i? _SEMICOLON? -> close
?io_type: ("Error"i | "stderr"i) -> stderr
    | ("Output"i | "stdout"i) -> stdout
?open_ext: ("Append"i | "Extend"i | "a"i) -> a
    | ("Overwrite"i | "w"i) -> w
    | ("No"i "Overwrite"i | "x"i) -> x

zip: "Create"i "Zip"i "File"i? expr (_COMMA? zip_option (_COMMA zip_option)*)? _SEMICOLON?
?zip_option: "Comment"i ("=" | "Is"i)? expr -> comment
    | "Include"i ("=" | "Is"i)? expr+ -> include
    | "Exclude"i ("=" | "Is"i)? expr+ -> exclude

exit: "Exit"i expr? _SEMICOLON?

sort: "Sort"i sort_source sort_keys? unique_clause? sort_target? _SEMICOLON?
sort_source: sort_obj -> source
sort_target: ("Into"i | "Giving"i) sort_obj -> target
?sort_obj: sort_file | sort_var
sort_file: "File"i? expr ("As"i? load_source_type)? -> file
sort_var: ("Variable"i | "Var"i) var_name -> var
sort_keys: ("On"i | "By"i) sort_key (_COMMA sort_key)* -> keys
sort_key: sort_dir? "Key"i? NAME -> key
?sort_dir: sort_asc | sort_des
sort_asc: "Ascending"i | "Asc"i -> asc
sort_des: "Descending"i | "Des"i -> des
unique_clause: "Unique"i ("On"i NAME (_COMMA NAME)*)? -> unique

select: "Select"i outputs? from_clause where_clause? product_clause? limit_clause? for_clause? _SEMICOLON?

?outputs: output (_COMMA output)* _COMMA?

output: expr
    | expr "As"i (NAME | ESCAPED_STRING) -> output_as

?from_clause: "From"i (var_from | file_from {EXTN_FROM})
var_from: ("Variable"i | "Var"i) var_name ("As"i NAME)?
file_from: "File"i expr load_source_type? ("As"i NAME)?

where_clause: "Where"i expr (_COMMA expr)*

?for_clause: "For"i (for_json | for_csv | for_markdown | for_text | for_template)

for_json: "JSON"i (_COMMA? json_option (_COMMA json_option)*)?
?json_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Root"i (("=" | "Is"i) expr)? -> root
    | "Indent"i (("=" | "Is"i) expr)? -> indent
    | "Compact"i (("=" | "Is"i) expr)? -> compact
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> include_nulls
    | "With"i? "Array"i "Wrapper"i (("=" | "Is"i) expr)? -> array_wrapper
    | ("Without"i | "No"i) "Array"i "Wrapper"i (("=" | "Is"i) expr)? -> no_array_wrapper
    | ("Sort"i "Keys"i? | "Sorted"i) (("=" | "Is"i) expr)? -> sort_keys

for_csv: "CSV"i (_COMMA? csv_option (_COMMA csv_option)*)?
?csv_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Delimiter"i ("=" | "Is"i) expr -> delimiter
    | "Quote"i ("Char"i | "Character"i) ("=" | "Is"i) expr -> quotechar
    | "Escape"i ("Char"i | "Character"i) ("=" | "Is"i) expr -> escapechar
    | "Line"i ("Ender"i | "Terminator"i) ("=" | "Is"i) expr -> lineterminator
    | "Quote"i ("=" | "Is"i) CSV_QUOTE_TYPE -> quoting
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers
CSV_QUOTE_TYPE: "Minimal"i | "All"i | "Nonnumeric"i | "None"i

for_markdown: "MarkDown"i (_COMMA? markdown_option (_COMMA markdown_option)*)?
?markdown_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers

for_template: TEMPLATE_TYPE? ("Template"i | "Jinja"i | "Jinja2"i) (template_filename | "Default"i)? (_COMMA? template_option (_COMMA template_option)*)?
TEMPLATE_TYPE: "Record"i | "Batch"i
template_filename: "File"i? expr
?template_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Auto"i "Escape"i (("=" | "Is"i) expr)? -> auto_escape
    | "Trim"i "Blocks"i? (("=" | "Is"i) expr)? -> trim_blocks
    | "Left"i "Strip"i "Blocks"i? (("=" | "Is"i) expr)? -> lstrip_blocks
    | "Keep"i "Last"i "Newline"i (("=" | "Is"i) expr)? -> keep_last_newline
    | "Chain"i "Undefined"i "Variables"i? (("=" | "Is"i) expr)? -> chain_undefined
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers

for_text: "Text"i (_COMMA? for_text_option (_COMMA for_text_option)*)?
?for_text_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> include_nulls
    | "Field"i "Seperator"i ("=" | "Is"i) expr -> field_sep
    | "Header"i "Seperator"i ("=" | "Is"i) expr -> header_sep
    | "Record"i "Seperator"i ("=" | "Is"i) expr -> record_sep

// Either LIMIT <number> (OFFSET <number>)?
// or FETCH FIRST <number> ROWS ONLY
limit_clause: _limit_offset | _fetch_first
_limit_offset: "Limit"i ("=" | "Is"i)? expr (_COMMA? "Offset"i ("=" | "Is"i)? expr)?
_fetch_first: "Fetch"i "First"i expr "Rows"i "Only"i

product_clause: "Cartesian"i? "Product"i product_cols
product_cols: "All"i -> all
    | "None"i -> none
    | col_spec (_COMMA col_spec)*
?col_spec: DEC_NUMBER // One based
    | NAME
    | ESCAPED_STRING
// TODO: option to say before or after limits

?expr: ternary | and_expr

ternary: expr "?" expr ":" expr -> c_ternary
//    | expr "if"i expr "else"i expr -> py_ternary // TODO collision with "real" If statement, but only when capitalized?
// When LC, it works, but if (true if 5<7 else false)  print "a" else print "b" end doesn't parse

?and_expr: or_expr
    | or_expr (("&&" | "And"i) or_expr)+ -> and_op

?or_expr: expr2
    | expr2 (("||" | "Or"i) expr2)+ -> or_op

// Flattening operations out here allows the parse tree to hold
// the operation type explicitly instead of a generic "OP" where
// we need to deal with aliases
?expr2: _LPAREN expr _RPAREN
    | "!" expr2 -> unary_not // must be expr2 not expr else it binds across and/or
    | expr2 _DOT "Stash"i _LPAREN var_name _RPAREN -> stash
    | expr2 _DOT function -> function_call
    | expr2 _DOT NAME -> deref
    // Polymorphic operations than *could* be chained
    | expr2 ("+" | "\uFF0B") expr2 -> add_op
    | expr2 ("-" | "\u2212") expr2 -> sub_op
    | expr2 ("*" | "\u00D7") expr2 -> mul_op
    | expr2 ("/" | "\u00F7") expr2 -> div_op
    | expr2 "//" expr2 -> fdiv_op
    | expr2 ("%" | "Mod"i) expr2 -> mod_op
    | expr2 ("**" | "Pow"i) expr2 -> pow_op
    | expr2 "&" expr2 -> bit_and_op
    | expr2 "|" expr2 -> bit_or_op
    | expr2 ("^" | "Xor"i) expr2 -> bit_xor_op
    | expr2 ("<<" | "LShift"i) expr2 -> shl_op
    | expr2 (">>" | "RShift"i) expr2 -> shr_op
    // Return bools, typically not "chained"
    // TODO does this mean the rhs can be an expression?
    | expr2 ("==" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i) expr2 -> eq_op
    | expr2 ("!=" | "<>" | "\u2260" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i | (("Doesnt"i | "Does"i? "Not"i) "Equal"i)) expr2 -> neq_op
    | expr2 ("<" | "Is"i? "Less"i "Than"i) expr2 -> lt_op
    | expr2 (">" | "Is"i? "Greater"i "Than"i) expr2 -> gt_op
    | expr2 ("<=" | "\u2264" | "Is"? "Not"i "Greater"i "Than"i) expr2 -> le_op
    | expr2 (">=" | "\u2265" | "Is"i? "Not"i "Less"i "Than"i) expr2 -> ge_op
    | expr2 "Is"i? "In"i expr2 -> in_op
    | expr2 "Is"i? "Not"i "In"i expr2 -> not_in_op
    | expr2 "Contains"i "Any"i? expr2 -> contains_op
    | expr2 "Contains"i "All"i expr2 -> contains_all_op
    | expr2 ("~" | "Matches"i "Any"i?) expr2 -> matches_op
    | expr2 "Matches"i "All"i expr2 -> matches_all_op
    | expr2 "~*" expr2 -> imatches_op
    | expr2 "!~" expr2 -> not_matches_op
    | expr2 "!~*" expr2 -> not_imatches_op
    // These are more fundemental objects
    | _OSB (expr (_COMMA expr)*)? _CSB -> array         // may become CARRAY at runtime
    | "{" (expr ":" expr (_COMMA expr ":" expr)*)? "}" -> dict
    | TRUE | FALSE
    | NONE
    | INF | NAN                                         // becomes FLOAT at runtime
    | ESCAPED_STRING                                    // becomes STRING at runtime
    | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | DEC_NUMBER // becomes INT at runtime
    | FLOAT_NUMBER                                      // becomes FLOAT at runtime
    | NAME -> var_ref

var_name: NAME (_DOT NAME)*

{EXTN_GRAMMAR}

{FUNCTIONS}

%import common.ESCAPED_STRING
%import common.WS
%ignore WS
