//----------------------------------------------------------
// VGR - A DSL for scripting reports
//----------------------------------------------------------

// Omitted from the parse tree
_COMMA: ","
_SEMICOLON: ";"

// Numeric values
// NB: octal and binary regexs are shorter than the length
//     of the decimal regex, so we need to boost their
//     priorities so the former's leading zero doesn't get
//     prematurely matched by the latter.
HEX_NUMBER.2: /0[xX](?:_?[0-9a-fA-F])+/
OCT_NUMBER.2: /0[oO](?:_?[0-7])+/
BIN_NUMBER.2: /0[bB](?:_?[01])+/
DEC_NUMBER: /-?[0-9](?:_?[0-9])*/
_SPECIAL_DEC: /[0-9](?:_?[0-9])*/
_EXP_PART: /[eE][+-][0-9](?:_?[0-9])*/
// NB: slight difference from Python as floats can't end with a "."
_DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC
FLOAT_NUMBER: "-"? (_SPECIAL_DEC _EXP_PART | _DECIMAL _EXP_PART?)

// This becomes either a FLOAT or INT (when no decimal referenced) at runtime
SUPERSCRIPT_FLOAT: /⁽[⁺⁻]?[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?⁾/
                 | /[⁺⁻]?[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?/

// TODO needs to be moved to code and injected here...
// NAMEs are generally "snake case", "kabab case", and mixed version of the two, with some limitations.
// For "kabab", it cannot start with a hyphen and an alpha character must follow a hyphen.
// This is an attempt to prevent some subtraction operations from looking like identifiers
// The following characters are permitted:
//     * '$' in the first position only
//     * '_'
//     * Latin characters (A-Z, a-z, \u00C0-\u00FF, \u0100-\u017F, \u0180-\u024F, \u1E00-\u1EFF)
//     * ASCII digits (0-9) except for the first character
//     * Greek letters (\u0370-\u03FF)
//     * Mathematical alphanumeric symbols (\U0001D400-\U0001D7FF - supplementary plane / 32bit Unicode)
//     * Optional suffix of one or more prime indicators (\u2032), double thru quad prime indicators (\u2033, \u2034, \u2057),
//       or a single subscripted digit (\u2080-\u2089)
// NB: Lark uses the Python re module, which cannot handle Unicode character classes like \u1D400-\u1D7FF
//     in the standard way for supplementary characters unless the Python build fully supports UTF-32 internally.
NAME: /[A-Za-z$_\u00C0-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF\u0370-\u03FF\U0001D400-\U0001D7FF](?:[A-Za-z0-9_\u00C0-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF\u0370-\u03FF\U0001D400-\U0001D7FF]|-+[A-Za-z\u00C0-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF\u0370-\u03FF\U0001D400-\U0001D7FF])*(?:\u2032+|[\u2033\u2034\u2057\u2080-\u2089])?/

opt_statements: statement*
statements: statement+
?statement: simple_statement
    | select
    | control_statements
    | def_statements
    {EXTN_STATEMENTS}

?simple_statement: assert
    | break
    | call
    | close
    | continue
    | debug
    | echo
    | exit
    | list_append
    | list_insert
    | list_prepend
    | list_remove
    | list_remove_first
    | list_remove_last
    | list_replace
    | load_from
    | log
    | open
    | pass
    | print
    | printf
    | reset
    | return
    | set
    | sleep
    | sort
    | source
    | swap
    | unset
    | verbose
    | zip

?control_statements: choose_statement
    | if_statement
    | unless_statement
    | while_statement
    | until_statement
    | foreach_statement
    | repeat_statement

?def_statements: "Define"i? "Function"i var_name def_params? ":"? def_body "End"i _SEMICOLON? -> def_function
def_params: "(" (NAME (_COMMA NAME)*)? ")" -> params
def_body: statement+ -> body

call: "Call"i "Function"i? var_name ("(" (expr (_COMMA expr)*)? ")")? _SEMICOLON?
    | "Call"i "Function"i? var_name ("(" (expr (_COMMA expr)*)? ")")? "Giving"i var_name _SEMICOLON? -> call_giving

if_statement: "If"i expr ("Then"i | "Do"i | ":")? statement+ else_clause? "End"i _SEMICOLON? -> if
unless_statement: "Unless"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> unless
while_statement: "While"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> while
until_statement: "Until"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> until
repeat_statement: "Repeat"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> repeat
foreach_statement: "ForEach"i var_name "In"i expr ("Do"i | ":")? statement+ "End"i _SEMICOLON? -> foreach
else_clause: "Else"i ("Do"i | ":")? statement+ -> else
break: "Break"i _SEMICOLON?
continue: "Continue"i _SEMICOLON?
return: "Return"i expr? _SEMICOLON?

op_eq: ("==" | "\u2175" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i)                       // Unicode ⩵ (two consecutive equals signs)
op_ne: ("!=" | "\u2260" | "<>" | "\u00AC=" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i ) // Unicode ≠ (not eq) and ¬ (not)
// NB: intentionally "not greater than or equal to" et al
op_lt: ("<" | "\uFF1C" | "Less"i "Than"i)                                                  // Unicode ＜ (fullwidth <)
op_gt: (">" | "\uFF1E" | "Greater"i "Than"i)                                               // Unicode ＞ (fullwidth >)
op_le: ("<=" | "\u2264" | "\u00AC>" | "!>") | ("Not"i op_gt)                               // Unicode ≤ (less than or equal to) and ¬ (not)
op_ge: (">=" | "\u2265" | "\u00AC<" | "!<") | ("Not"i op_lt)                               // Unicode ≥ (greater than or equal to) and ¬ (not)
op_contains: "Contains"i
op_not_contains: ("Not"i op_contains | "Does"i "Not"i "Contain"i)
op_matches: "~" | "Matches"i
op_not_matches: ("!~" | "Not"i op_matches | "Does"i "Not"i "Match"i)
op_imatches: "~*"
op_not_imatches: "!~*" | "Not"i op_imatches

choose_statement: "Choose"i choose_all? ":" choice_block+ otherwise_block? "End"i _SEMICOLON? -> choose
    | "Choose"i choose_all? "Using"i expr ":" values_block+ otherwise_block? "End"i _SEMICOLON? -> choose_using
choose_all: "All"i
choice_block: "When"i expr ":" statement+
values_block: "When"i "Is"i? "Empty"i ":" statement+ -> is_empty_block
    | "When"i "Is"i? "Not"i "Empty"i ":" statement+ -> is_not_empty_block
    | "When"i value_list ":" statement+
    | "When"i "Not"i value_list ":" statement+ -> not_values_block
    | "When"i expr ("Through"i | "Thru"i | "To"i) expr ":" statement+ -> range_block
    | "When"i "Not"i expr ("Through"i | "Thru"i | "To"i) expr ":" statement+ -> not_range_block
    | "When"i (op_lt | op_gt | op_ge | op_le) expr ":" statement+ -> ineq_block
    | "When"i (op_eq | op_ne | op_contains | op_matches | op_not_contains | op_not_matches) value_list ":" statement+
value_list: expr (_COMMA expr)*
otherwise_block: "Otherwise"i ":" statement+

// simple boolean on/off, true/false
// these are "proper statements" as they control the behavior of other statements
debug: "Debug"i expr? _SEMICOLON?
echo: "Echo"i expr? _SEMICOLON?
verbose: "Verbose"i expr? _SEMICOLON?

pass: ("Pass"i | "Nop"i) _SEMICOLON?

sleep: "Sleep"i "For"i? expr ("Seconds"i | "Second"i)? _SEMICOLON?

set:  ("Set"i "Variable"i?)? var_name ("=" | "To"i) expr _SEMICOLON?
    | ("Set"i "Variable"i?)? var_name ("=" | "To"i)? def_params? ("->" | "=>" | "\u2192") expr _SEMICOLON? -> set_arrow
    | ("Set"i "Variable"i?)? var_name ("=" | "To"i)? def_params? ("->" | "=>" | "\u2192") "Compile"i "(" expr ")" _SEMICOLON? -> compile_arrow
    | ("Set"i "Variable"i?)? var_name IN_PLACE_OP expr _SEMICOLON? -> set_in_place
IN_PLACE_OP: ("+=" | "-=" | "*=" | "/=" | "%=" | "**=" | "&=" | "|=" | "^=" | "<<=" | ">>=" )

swap: "Swap"i "Variable"i? var_name "With"i "Variable"i? var_name _SEMICOLON?
    | "Swap"i "Variables"i? var_name "And"i var_name _SEMICOLON?

unset: "Unset"i "Variable"i? var_name (_COMMA var_name)* _SEMICOLON?

reset: "Reset"i reset_opt (_COMMA? reset_opt)* _SEMICOLON?
?reset_opt: "All"i -> all
    | "Data"i -> data
    | "Args"i -> args
    | "Output"i -> output

source: "Source"i _SEMICOLON
    | "Source"i "From"i? ("File"i | "Files"i)? expr (_COMMA expr)* _SEMICOLON?

// TODO needs to have an encoding value (defaults to utf-8-sig)
load_from: "Load"i "Variable"i? var_name ("From"i | "With"i) "File"i? expr ("As"i? load_source_type)? _SEMICOLON?
load_source_type: "JSON"i "Object"i? -> json_object
    | "JSON"i "Object"i? "Per"i "Line"i -> json_objects
    | "CSV"i -> csv_file
    | "Text"i ("Lines"i | "Line"i) -> text_lines
    | "Text"i -> text_file

assert: "Assert"i expr (":" expr (_COMMA expr)*)? _SEMICOLON?

print: "Print"i (expr (_COMMA expr)*)? _SEMICOLON?
printf: "Printf"i (expr (_COMMA expr)*)? _SEMICOLON?

log: "Log"i log_level expr (_COMMA expr)* _SEMICOLON?
   | "Log"i "Level"i log_level _SEMICOLON? -> log_setlevel
?log_level: "Debug"i -> debug
    | "Info"i -> info
    | ("Warn"i | "Warning"i) -> warn
    | "Error"i -> error

open: "Open"i io_type "File"i? expr open_ext? _SEMICOLON?
close: "Close"i io_type "File"i? _SEMICOLON?
?io_type: ("Error"i | "stderr"i) -> stderr
    | ("Output"i | "stdout"i | "sysprint"i) -> stdout
    | ("Input"i | "stdin"i | "sysin"i) -> stdin
?open_ext: ("Append"i | "Extend"i | "a"i) -> a
    | ("Overwrite"i | "w"i) -> w
    | ("No"i "Overwrite"i | "x"i) -> x
    | ("Read"i | "r"i) -> r

zip: "Create"i "Zip"i "File"i? expr (_COMMA? zip_option (_COMMA zip_option)*)? _SEMICOLON?
?zip_option: "Comment"i ("=" | "Is"i)? expr -> comment
    | "Include"i ("=" | "Is"i)? expr+ -> include
    | "Exclude"i ("=" | "Is"i)? expr+ -> exclude

exit: "Exit"i expr? _SEMICOLON?

sort: "Sort"i sort_source sort_keys? unique_clause? sort_target? _SEMICOLON?
sort_source: sort_obj -> source
sort_target: ("Into"i | "Giving"i) sort_obj -> target
?sort_obj: sort_file | sort_var
sort_file: "File"i expr ("As"i? load_source_type)? -> file
sort_var: "Variable"i? var_name -> var
sort_keys: ("On"i | "By"i) sort_key (_COMMA sort_key)* -> keys
sort_key: sort_dir? "Key"i? expr -> key
?sort_dir: sort_asc | sort_des
sort_asc: "Ascending"i | "Asc"i -> asc
sort_des: "Descending"i | "Des"i -> des
unique_clause: "Unique"i ("On"i expr (_COMMA expr)*)? -> unique

list_append: "Append"i list_all? expr "To"i "List"i? var_name _SEMICOLON?
list_prepend: "Prepend"i list_all? expr "To"i "List"i? var_name _SEMICOLON?
list_insert: "Insert"i list_all? expr "Into"i "List"i? var_name "At"i ("Pos"i | "Position"i | "Index"i)? expr _SEMICOLON?
list_remove: "Remove"i expr "From"i "List"i? var_name list_giving? _SEMICOLON?
list_remove_first: "Remove"i "First"i "Item"i? "From"i "List"i? var_name list_giving? _SEMICOLON?
list_remove_last: "Remove"i "Last"i "Item"i? "From"i "List"i? var_name list_giving? _SEMICOLON?
list_replace: "Replace"i expr "In"i "List"i? var_name "With"i expr list_giving? _SEMICOLON?
list_all: "All"i
?list_giving: "Giving"i var_name

select: "Select"i outputs? from_clause where_clause? product_clause? limit_clause? for_clause? _SEMICOLON?

?outputs: output (_COMMA output)* _COMMA?

output: expr
    | expr "As"i expr -> output_as

?from_clause: "From"i (var_from | file_from {EXTN_FROM})
var_from: "Variable"i? var_name ("As"i expr)?
file_from: "File"i expr ("As"i expr)?
    | "File"i expr load_source_type ("As"i expr)? -> file_from_typed

where_clause: "Where"i expr (_COMMA expr)*

?for_clause: "For"i (for_json | for_csv | for_markdown | for_text | for_template)

for_json: "JSON"i (_COMMA? json_option (_COMMA json_option)*)?
?json_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Root"i (("=" | "Is"i) expr)? -> root
    | "Indent"i (("=" | "Is"i) expr)? -> indent
    | "Compact"i (("=" | "Is"i) expr)? -> compact
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> include_nulls
    | "With"i? "Array"i "Wrapper"i (("=" | "Is"i) expr)? -> array_wrapper
    | ("Without"i | "No"i) "Array"i "Wrapper"i (("=" | "Is"i) expr)? -> no_array_wrapper
    | ("Sort"i "Keys"i? | "Sorted"i) (("=" | "Is"i) expr)? -> sort_keys

for_csv: "CSV"i (_COMMA? csv_option (_COMMA csv_option)*)?
?csv_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Delimiter"i ("=" | "Is"i) expr -> delimiter
    | "Quote"i ("Char"i | "Character"i) ("=" | "Is"i) expr -> quotechar
    | "Escape"i ("Char"i | "Character"i) ("=" | "Is"i) expr -> escapechar
    | "Line"i ("Ender"i | "Terminator"i) ("=" | "Is"i) expr -> lineterminator
    | "Quote"i ("=" | "Is"i) CSV_QUOTE_TYPE -> quoting
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers
CSV_QUOTE_TYPE: "Minimal"i | "All"i | "Nonnumeric"i | "None"i

for_markdown: "MarkDown"i (_COMMA? markdown_option (_COMMA markdown_option)*)?
?markdown_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers

for_template: template_type? ("Template"i | "Jinja"i | "Jinja2"i) (template_filename | "Default"i)? (_COMMA? template_option (_COMMA template_option)*)?
?template_type: "Record"i -> record
    | "Batch"i -> batch
template_filename: "File"i? expr
?template_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Auto"i "Escape"i (("=" | "Is"i) expr)? -> auto_escape
    | "Trim"i "Blocks"i? (("=" | "Is"i) expr)? -> trim_blocks
    | "Left"i "Strip"i "Blocks"i? (("=" | "Is"i) expr)? -> lstrip_blocks
    | "Keep"i "Last"i "Newline"i (("=" | "Is"i) expr)? -> keep_last_newline
    | "Chain"i "Undefined"i "Variables"i? (("=" | "Is"i) expr)? -> chain_undefined
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers

for_text: "Text"i (_COMMA? for_text_option (_COMMA for_text_option)*)?
?for_text_option: "Encode"i? "Ascii"i (("=" | "Is"i) expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | "Is"i) expr)? -> encode_unicode
    | "Include"i "Headers"i (("=" | "Is"i) expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | "Is"i) expr)? -> omit_headers
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | "Is"i) expr)? -> include_nulls
    | "Field"i "Seperator"i ("=" | "Is"i) expr -> field_sep
    | "Header"i "Seperator"i ("=" | "Is"i) expr -> header_sep
    | "Record"i "Seperator"i ("=" | "Is"i) expr -> record_sep

// Either LIMIT <number> (OFFSET <number>)?
// or FETCH FIRST <number> ROWS ONLY
limit_clause: _limit_offset | _fetch_first
_limit_offset: "Limit"i ("=" | "Is"i)? expr (_COMMA? "Offset"i ("=" | "Is"i)? expr)?
_fetch_first: "Fetch"i "First"i expr "Rows"i "Only"i

product_clause: "Cartesian"i? "Product"i product_cols
product_cols: "All"i -> all
    | "None"i -> none
    | col_spec (_COMMA col_spec)*
?col_spec: DEC_NUMBER // One based
    | NAME
    | STRING
// TODO: option to say before or after limits

?expr: ternary | and_expr

ternary: expr "?" expr ":" expr -> c_ternary
//    | expr "If"i expr "Else"i expr -> py_ternary // TODO collision with "real" If statement, but only when capitalized?
// When LC, it works, but if (true if 5<7 else false)  print "a" else print "b" end doesn't parse

?and_expr: or_expr
    | or_expr (("&&" | "\u2227" | "And"i) or_expr)+ -> and_op // Unicode ∧ (conjunction)

?or_expr: expr2
    | expr2 (("||" | "\u2228" | "Or"i) expr2)+ -> or_op // Unicode ∨ (disjunction)

// Flattening operations out here allows the parse tree to hold
// the operation type explicitly instead of a generic "OP" where
// we need to deal with aliases
?expr2: atom
    | "(" expr ")"
    // must be expr2 not expr else it binds across and/or
    | ("!" | "\uFF01" | "\u00AC") expr2 -> unary_not // Unicode ！(fullwidth excl) and ¬ (logical not)
    | expr2 "." ("SetVar"i | "set_var"i) "(" var_name ")" -> set_var
    | expr2 "." function -> function_call
    | expr2 "." NAME -> deref
    | expr2 "." "@" var_name "(" (expr (_COMMA expr)*)? ")" -> invoke_func_inline
    | "@" var_name "(" (expr (_COMMA expr)*)? ")" -> invoke_func
    // Polymorphic operations than *could* be chained
    | expr2 ("+" | "\uFF0B") expr2 -> add_op // Unicode ＋ (fullwidth plus)
    | expr2 ("-" | "\u2212" | "\uFF0D") expr2 -> sub_op // Unicode − (minus sign) and － (fullwidth minus)
    | expr2 ("*" | "\u00D7") expr2 -> mul_op // Unicode × (multiplication)
    | expr2 ("/" | "\u00F7") expr2 -> div_op // Unicode ÷ (division)
    | expr2 "%" expr2 -> mod_op
    | expr2 "**" expr2 -> pow_op
    | expr2 "&" expr2 -> bit_and_op
    | expr2 "|" expr2 -> bit_or_op
    | expr2 "^" expr2 -> bit_xor_op
    | expr2 "<<" expr2 -> shl_op
    | expr2 ">>" expr2 -> shr_op
    // Return bools, typically not "chained"
    | expr2 ("===") expr2 -> exact_eq_op
    | expr2 ("==" | "\u2175" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i) expr2 -> eq_op // Unicode ⩵ (two consecutive equals signs)
    | expr2 ("!=" | "\u2260" | "<>" | "\u00AC=" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i ) expr2 -> neq_op // Unicode ≠ (not eq) and ¬ (not)
    | expr2 ("<" | "\uFF1C" | "Is"i? "Less"i "Than"i) expr2 -> lt_op // Unicode ＜ (fullwidth <)
    | expr2 (">" | "\uFF1E" | "Is"i? "Greater"i "Than"i) expr2 -> gt_op // Unicode ＞ (fullwidth >)
    | expr2 ("<=" | "\u2264" | "\u00AC>" | "!>" | "Is"? "Not"i "Greater"i "Than"i) expr2 -> le_op // Unicode ≤ (less than or equal to) and ¬ (not)
    | expr2 (">=" | "\u2265" | "\u00AC<" | "!<" | "Is"i? "Not"i "Less"i "Than"i) expr2 -> ge_op // Unicode ≥ (greater than or equal to) and ¬ (not)
    | expr2 (("Is"i? "In"i) | "\u2208") expr2 -> in_op // Unicode ∈ (element of)
    | expr2 (("Is"i? "Not"i "In"i) | "\u2209") expr2 -> not_in_op // Unicode ∉ (not an element of)
    | expr2 "Contains"i "Any"i? expr2 -> contains_op
    | expr2 "Contains"i "All"i expr2 -> contains_all_op
    | expr2 ("~" | "Matches"i "Any"i?) expr2 -> matches_op
    | expr2 "Matches"i "All"i expr2 -> matches_all_op
    | expr2 "~*" expr2 -> imatches_op
    | expr2 "!~" expr2 -> not_matches_op
    | expr2 "!~*" expr2 -> not_imatches_op
    // Misc operations
    | "\u2308" expr "\u2309" -> ceil_op                 // Unicode ceiling ⌈ x ⌉
    | "\u230A" expr "\u230B" -> floor_op                // Unicode floor ⌊ x ⌋
    | expr2 SUPERSCRIPT_FLOAT -> pow_op
    | "[" (expr (_COMMA expr)*)? _COMMA? "]" -> array
    | "{" (expr ":" expr (_COMMA expr ":" expr)*)? _COMMA? "}" -> dict

?atom: ("True"i  | "\u22A4") -> vtrue                   // Unicode ⊤ (top)
    | ("False"i | "\u22A5") -> vfalse                   // Unicode ⊥ (bottom)
    | ("None"i  | "\u2205" | "Null"i) -> vnone          // Unicode ∅ (Empty set)
    | ("Inf"i   | "\u221E") -> vinf                     // Unicode ∞ (infinity)
    | "Nan"i -> vnan
    | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | DEC_NUMBER // becomes INT at runtime
    | FLOAT_NUMBER                                      // becomes FLOAT at runtime
    | STRING
    | NAME -> var_ref

var_name: NAME ("." NAME)*

{EXTN_GRAMMAR}

{FUNCTIONS}

// modified versions of python.STRING/LONG_STRING : removed the [ufb]
_STRING: /[Rr]?("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/
_LONG_STRING: /[Rr]?(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?''')/s
// Allow typographic quotes from C/P sources, but fix them up internally
_MS_STRING: /[Rr]?(\u201C(?!"").*?(?<!\\)(\\\\)*?\u201D|\u2018(?!'').*?(?<!\\)(\\\\)*?\u2019)/
STRING: _STRING | _LONG_STRING | _MS_STRING

SH_COMMENT: /#[^\n]*/
CPP_COMMENT: /\/\/[^\n]*/
C_COMMENT: "/*" /(.|\n)*?/ "*/"
SQL_COMMENT: /--[^\n]*/

%import common.WS
%ignore WS
%ignore SH_COMMENT
%ignore C_COMMENT
%ignore CPP_COMMENT
%ignore SQL_COMMENT
