// Omitted from the parse tree
_DOT: "."
_COMMA: ","
_LPAREN: "("
_RPAREN: ")"
_SEMICOLON: ";"
_OSB: "["
_CSB: "]"

// Converted to their literal values after parsing
TRUE.90: "true"i
FALSE.90: "false"i
NONE.90: "none"i | "null"i
INF.90: "inf"i
NAN.90: "nan"i

// Numeric values
// NB: octal and binary regexs are shorter than the length
//     of the decimal regex, so we need to boost their
//     priorities so the former's leading zero doesn't get
//     prematurely matched by the latter.
HEX_NUMBER.2: /0[xX](_?[0-9a-fA-F])+/
OCT_NUMBER.2: /0[oO](_?[0-7])+/
BIN_NUMBER.2: /0[bB](_?[01])+/
DEC_NUMBER: /[+-]?[0-9](_?[0-9])*/
_SPECIAL_DEC: /[0-9](_?[0-9])*/
_EXP_PART: /[eE][+-][0-9](_?[0-9])*/
// NB: slight difference from Python as floats can't end with a "."
_DECIMAL: _DOT _SPECIAL_DEC | _SPECIAL_DEC _DOT _SPECIAL_DEC
FLOAT_NUMBER: /[+-]/? (_SPECIAL_DEC _EXP_PART | _DECIMAL _EXP_PART?)

// "snake case", "kabab case", and mixed version of the two
// For "kabab", it cannot start with a hyphen and an alpha character must follow a hyphen
// This is an attempt to prevent some subtraction operations from looking like identifiers
NAME: /[A-Za-z_]([A-Za-z0-9_]|-+[A-Za-z])*/

statements: statement+
?statement: assert
    | close
    | debug
    | echo
    | exhibit
    | exit
    | load_from
    | open
    | print
    | printf
    | select
    | set
    | verbose
    | zip

// TODO: RSN
// unset: "Unset"i var_name _SEMICOLON?
// source: "Source"i (expr (_COMMA expr)*)? _SEMICOLON?

// simple boolean on/off, true/false
// these are "proper statements" as they control the behavior of other statements
debug: "Debug"i (("=" | ":=" | "Is"i)? expr)? _SEMICOLON?
echo: "Echo"i (("=" | ":=" | "Is"i)? expr)? _SEMICOLON?
verbose: "Verbose"i (("=" | ":=" | "Is"i)? expr)? expr? _SEMICOLON?

set: "Let"i var_name ("=" | ":=") expr _SEMICOLON?
    | "Set"i var_name ("=" | ":=" | "To"i) expr _SEMICOLON?

load_from: "Load"i var_name "From"i "File"i? expr load_source_type? _SEMICOLON?
load_source_type: "JSON"i "Object"i? -> json_object
    | "JSON"i "Object"i? "Per"i "Line"i -> json_objects
    | "CSV"i -> csv_file
    | "TEXT"i -> text_file

assert: "Assert"i (expr (":" expr (_COMMA expr)*)?)? _SEMICOLON?

printf: "Printf"i (expr (_COMMA expr)*)? _SEMICOLON?

print: "Print"i (expr (_COMMA expr)*)? _SEMICOLON?

exhibit: "Exhibit"i (var_name (_COMMA var_name)*)? _SEMICOLON?

open: "Open"i io_type "File"i? expr open_ext? _SEMICOLON?
?io_type: ("Error"i | "stderr"i) -> stderr
    | ("Output"i | "stdout"i) -> stdout
?open_ext: ("Append"i | "Extend"i | "a"i) -> a
    | ("Overwrite"i | "w"i) -> w
    | ("No"i "Overwrite"i | "x"i) -> x
close: "Close"i io_type "File"i? _SEMICOLON? -> close

zip: "Create"i "Zip"i "File"i? expr (_COMMA? zip_option (_COMMA zip_option)*)? _SEMICOLON?
?zip_option: "Password"i expr -> password
    | "Comment"i ("=" | ":=")? expr -> comment
    | "Include"i ("=" | ":=")? expr+ -> include
    | "Exclude"i ("=" | ":=")? expr+ -> exclude

exit: "Exit"i expr? _SEMICOLON?

select: "Select"i outputs? "From"i TARGET where_clause? product_clause? limit_clause? for_clause? _SEMICOLON?

// TODO Future (join_clause+ | auto_join_clause)?

?for_clause: "For"i for_json
    | "For"i for_csv
    | "For"i for_markdown
    | "For"i for_template

for_json: "JSON"i (_COMMA? json_option (_COMMA json_option)*)?
?json_option: "Encode"i? "Ascii"i (("=" | ":=") expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | ":=") expr)? -> encode_unicode
    | "Root"i (("=" | ":=") expr)? -> root
    | "Indent"i (("=" | ":=") expr)? -> indent
    | "Compact"i (("=" | ":=") expr)? -> compact
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | ":=") expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | ":=") expr)? -> include_nulls
    | "With"i? "Array"i "Wrapper"i (("=" | ":=") expr)? -> array_wrapper
    | ("Without"i | "No"i) "Array"i "Wrapper"i (("=" | ":=") expr)? -> no_array_wrapper
    | ("Sort"i "Keys"i? | "Sorted"i) (("=" | ":=") expr)? -> sort_keys

for_csv: "CSV"i (_COMMA? csv_option (_COMMA csv_option)*)?
?csv_option: "Encode"i? "Ascii"i (("=" | ":=") expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | ":=") expr)? -> encode_unicode
    | "Delimiter"i ("=" | ":=") expr -> delimiter
    | "Quote"i ("Char"i | "Character"i) ("=" | ":=") expr -> quotechar
    | "Escape"i ("Char"i | "Character"i) ("=" | ":=") expr -> escapechar
    | "Line"i ("Ender"i | "Terminator"i) ("=" | ":=") expr -> lineterminator
    | "Quote"i ("=" | ":=") CSV_QUOTE_TYPE -> quoting
    | "Include"i "Headers"i (("=" | ":=") expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | ":=") expr)? -> omit_headers
CSV_QUOTE_TYPE: "Minimal"i | "All"i | "Nonnumeric"i | "None"i

for_markdown: "MarkDown"i (_COMMA? markdown_option (_COMMA markdown_option)*)?
?markdown_option: "Encode"i? "Ascii"i (("=" | ":=") expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | ":=") expr)? -> encode_unicode
    | "Include"i "Headers"i (("=" | ":=") expr)? -> include_headers
    | ("No"i | "Omit"i) "Headers"i (("=" | ":=") expr)? -> omit_headers

for_template: TEMPLATE_TYPE? "Template"i "File"i? expr (_COMMA? template_option (_COMMA template_option)*)?
TEMPLATE_TYPE: "Record"i | "Batch"i
?template_option: "Encode"i? "Ascii"i (("=" | ":=") expr)? -> encode_ascii
    | "Encode"i? ("Unicode"i | "UTF8"i | "UTF-8"i) (("=" | ":=") expr)? -> encode_unicode
    | "Auto"i "Escape"i (("=" | ":=") expr)? -> auto_escape
    | "Debug"i (("=" | ":=") expr)? -> debug
    | "Exclude"i ("Nulls"i | "Null"i "Values"i) (("=" | ":=") expr)? -> exclude_nulls
    | "Include"i ("Nulls"i | "Null"i "Values"i) (("=" | ":=") expr)? -> include_nulls
// TODO    | "Tags"i expr -> tags

// TODO future
//join_clause: "Join"i TARGET "To"i NAME join_as? join_using?
//join_as: "As"i (NAME | ESCAPED_STRING)
//join_using: "Using"i attr_ref (_COMMA attr_ref)*
//attr_ref: NAME (_DOT (NAME))+
//auto_join_clause: "Auto"i "Join"i auto_join?
//?auto_join: "All"i -> all
//    | "None"i -> none
//    | NAME (_COMMA NAME)*

?outputs: (output (_COMMA output)*)

output: expr
    | expr "As"i (NAME | ESCAPED_STRING) -> output_as

where_clause: "Where"i expr (("And"i | "&&") expr)*

// Either LIMIT <number> (OFFSET <number>)?
// or FETCH FIRST <number> ROWS ONLY
limit_clause: _limit_offset | _fetch_first
_limit_offset: "Limit"i ("=" | ":=")? expr (_COMMA? "Offset"i ("=" | ":=")? expr)?
_fetch_first: "Fetch"i "First"i expr "Rows"i "Only"i

product_clause: "Cartesian"i? "Product"i product_cols
product_cols: "All"i -> all
    | "None"i -> none
    | col_spec (_COMMA col_spec)*
?col_spec: DEC_NUMBER // One based
    | NAME
    | ESCAPED_STRING
// TODO: option to say before or after limits

// Flattening operations out here allows the parse tree to hold
// the operation type explicitly instead of a generic "OP" where
// we need to deal with aliases
?expr: _LPAREN expr _RPAREN
    | "!" expr -> unary_not
    | expr _DOT function -> function_call
    | expr _DOT NAME -> deref
    | expr ("||" | "Or"i) expr -> or_op
    | expr ("+" | "\uFF0B") expr -> add_op
    | expr ("-" | "\u2212") expr -> sub_op
    | expr ("*" | "\u00D7") expr -> mul_op
    | expr ("/" | "\u00F7") expr -> div_op
    | expr "//" expr -> fdiv_op
    | expr ("%" | "Mod"i) expr -> mod_op
    | expr ("**" | "Pow"i) expr -> pow_op
    | expr "&" expr -> bit_and_op
    | expr "|" expr -> bit_or_op
    | expr ("^" | "Xor"i) expr -> bit_xor_op
    | expr ("<<" | "LShift"i) expr -> shl_op
    | expr (">>" | "RShift"i) expr -> shr_op
    | expr ("==" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i) expr -> eq_op
    | expr ("!=" | "<>" | "\u2260" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i | (("Doesnt"i | "Does"i? "Not"i) "Equal"i)) expr -> neq_op
    | expr ("<" | "Is"i? "Less"i "Than"i) expr -> lt_op
    | expr (">" | "Is"i? "Greater"i "Than"i) expr -> gt_op
    | expr ("<=" | "\u2264" | "Is"? "Not"i "Greater"i "Than"i) expr -> le_op
    | expr (">=" | "\u2265" | "Is"i? "Not"i "Less"i "Than"i) expr -> ge_op
    | expr "Is"i? "In"i expr -> in_op
    | expr "Is"i? "Not"i "In"i expr -> not_in_op
    | expr "Contains"i expr -> contains_op
    | expr (("Doesnt"i | "Does"i? "Not"i) "Contain"i) expr -> not_contains_op
    | expr ("~" | "Match"i | "Matches"i) expr -> match_op
    | expr ("IMatch"i | "IMatches"i) expr -> imatch_op
    | expr ("!~" | ("Doesnt"i | "Does"i? "Not"i) "Match"i) expr -> not_match_op
    | expr (("Doesnt"i | "Does"i? "Not"i) "IMatch"i) expr -> not_imatch_op
    | _OSB (expr (_COMMA expr)*)? _CSB -> array         // may become CARRAY at runtime
    | TRUE | FALSE
    | NONE
    | INF | NAN                                         // becomes FLOAT at runtime
    | ESCAPED_STRING                                    // becomes STRING at runtime
    | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | DEC_NUMBER // becomes INT at runtime
    | FLOAT_NUMBER                                      // becomes FLOAT at runtime
    | NAME -> var_ref

var_name: NAME (_DOT NAME)*

// ---- BEGIN GENERATED CODE ----

{GENERATED_CODE}

// ---- END GENERATED CODE ----

%import common.ESCAPED_STRING
%import common.WS
%ignore WS
