?basic_statements: basic_continue
    | basic_do_until
    | basic_do_while
    | basic_for_next_by
    | basic_for_next
    | basic_exit
    | basic_let
    | basic_troff
    | basic_tron


// Note the "addition" of the optional colon following the control statements
// While not part of the BASIC syntax, VGR common syntax uses it, so it is
// optional here to prevent excessive syntax errors.
basic_do_while: "Do"i "While"i expr ":"? statement+ "Loop"i _SEMICOLON?
basic_do_until: "Do"i "Until"i expr ":"? statement+ "Loop"i _SEMICOLON?
basic_for_next_by: "For"i var_name "=" expr "To"i expr "By"i expr ":"? statement+ "Next"i _SEMICOLON?
basic_for_next: "For"i var_name "=" expr "To"i expr ":"? statement+ "Next"i _SEMICOLON?
basic_exit: "Exit"i ("Do"i | "For"i | "While"i) _SEMICOLON?
basic_continue: "Continue"i ("Do"i | "For"i | "While"i) _SEMICOLON?
basic_let: "Let"i var_name "=" expr _SEMICOLON?
basic_troff: "Troff"i _SEMICOLON?
basic_tron: "Tron"i _SEMICOLON?

// Prototype not working: conflicts with the "Select" statement
// basic_select_case: "Select"i "Case"i expr ":"? case_values_block+ case_else_block? "End"i "Select"i _SEMICOLON? -> choose_using
// case_values_block: "Case"i value_list ":"? statement+ -> values_block
// case_else_block: "Case"i "Else"i ":"? statement+ -> otherwise_block
