//----------------------------------------------------------
// VGR - A DSL for scripting reports
//----------------------------------------------------------

// These are functionally named, but as terminals,
// you should use them anywhere the characters are required.
_CLAUSE_SEP: ":"
_SEP: ","

// Numeric values
// NB: octal and binary regexs are shorter than the length
//     of the decimal regex, so we need to boost their
//     priorities so the former's leading zero doesn't get
//     prematurely matched by the latter.
HEX_NUMBER.2: /0[xX](?:_?[0-9a-fA-F])+/
OCT_NUMBER.2: /0[oO](?:_?[0-7])+/
BIN_NUMBER.2: /0[bB](?:_?[01])+/
DEC_NUMBER: /-?[0-9](?:_?[0-9])*/
_SPECIAL_DEC: /[0-9](?:_?[0-9])*/
_EXP_PART: /[eE][+-][0-9](?:_?[0-9])*/
// NB: slight difference from Python as floats can't end with a "."
_DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC
FLOAT_NUMBER: "-"? (_SPECIAL_DEC _EXP_PART | _DECIMAL _EXP_PART?)

// This becomes either a FLOAT or INT (when no decimal referenced) at runtime
SUPERSCRIPT_FLOAT: /⁽[⁺⁻]?(?:[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?|·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)⁾|[⁺⁻]?(?:[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?|·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)/

// NB: This pattern is very long and tends to win out over keyword tokens
//     If it's priority is set lower, you need to adjust the priority on
//     ALL tokens
NAME: /{VAR_NAME}/

//----------------------------------------------------------
_EQ: "="
_assignment: _EQ | "To"i
_file_option: "File"i
_files_option: "File"i | "Files"i
_headers_option: "Header"i | "Headers"i
_null_values_option: "Nulls"i | "Null"i "Values"i
_unit_seconds: "Second"i | "Seconds"i
//----------------------------------------------------------

//----------------------------------------------------------
// Templates
//----------------------------------------------------------
// Comma separated list
_csep_list{t_type}: t_type (_SEP t_type)*
// Used for a list of options in a statement
_options_list{t_type}: (_SEP? t_type (_SEP? t_type)*)?
//----------------------------------------------------------

opt_statements: statement*

// NB: this is the only place where we have to reference the optional statement ender
?statement: (simple_statement | select | control_statements | define_statements {EXTN_STATEMENTS}) ";"?
    | ";" -> pass // blank statement synonymous with "pass"

?simple_statement: abort
    | accept_input
    | add_giving
    | add_to
    | assert
    | assign
    | break
    | call
    | close
    | const
    | continue
    | debug
    | declare
    | div_by
    | echo
    | exhibit
    | exit
    | include
    | list_append
    | list_insert
    | list_prepend
    | list_remove
    | list_remove_first
    | list_remove_last
    | list_replace
    | load_from
    | log
    | mul_by
    | open
    | pass
    | print
    | printf
    | remove_key
    | reset
    | return
    | set
    | set_key_value
    | sleep
    | sort
    | source
    | sub_from
    | sub_giving
    | swap
    | unset
    | verbose
    | zip

?control_statements: block_statement
    | choose_statement
    | for_next
    | foreach_statement
    | if_statement
    | repeat_statement
    | unless_statement
    | until_statement
    | while_statement

// Some common patterns
?giving_clause: "Giving"i var_name
?option_value: "Is"i? expr
stderr: ("Error"i | "stderr"i)
stdout: ("Output"i | "stdout"i)
stdin: ("Input"i | "stdin"i)
encoding: "Encoding"i option_value

block_statement: "Begin"i _CLAUSE_SEP? statement+ "End"i -> block

call: _call_function var_name ("(" _csep_list{expr}? ")")?
    | _call_function var_name ("(" _csep_list{expr}? ")")? giving_clause -> call_giving
    | _call_function var_name "Using"i _csep_list{expr}
    | _call_function var_name "Using"i _csep_list{expr} giving_clause -> call_giving
_call_function: ("Call-Function"i | "Call"i "Function"i?)

declare: _decl _csep_list{var_name}
    |    _decl _csep_list{var_name} "As"i? "Local"i  -> declare_local
    |    _decl _csep_list{var_name} "As"i? "Global"i -> declare_global
_decl: "Declare"i


function_def: "Define"i? func_modifier* "Function"i
func_modifier: ("Constant"i | "Const"i)               -> mod_const
    |          ("Cached"i | "Cache"i) ("(" expr ")")? -> mod_cached
_function_arrow: "->" | "=>" | "\u2192"
define_statements: function_def var_name func_params? _CLAUSE_SEP? func_body ("End-Function"i | "End"i) -> def_function
    |              function_def var_name func_params? _function_arrow expr                              -> def_arrow
    |              function_def var_name func_params? _function_arrow "Compile"i "(" expr ")"           -> compile_arrow
// NB: doesn't work with template; probably should be changed to use var_name anyway
func_params: "(" (NAME (_SEP NAME)*)? ")" -> params
func_body: statement+ -> body

// Note: this combines BASIC-like syntax (For Each) and VGR (For-Each)
foreach_statement: ("For-Each"i | "For"i "Each"i) var_name "In"i expr _CLAUSE_SEP? statement+ _end_for -> foreach

for_next: "For"i var_name _EQ expr "To"i expr _CLAUSE_SEP? statement+ _end_for
    |     "For"i var_name _EQ expr "To"i expr "Step"i expr _CLAUSE_SEP? statement+ _end_for -> for_next_by
_end_for: "End-For"i | "Next"i | "End"i

// The addition of the optional "Then" allows a BASIC-like If syntax usage
if_statement: "If"i expr ("Then"i | _CLAUSE_SEP)? statement+ else_clause? ("End-If"i | "End"i) -> if
else_clause: "Else"i _CLAUSE_SEP? statement+ -> else

repeat_statement: "Repeat"i expr ("Time"i | "Times"i)? _CLAUSE_SEP? statement+ ("End-Repeat"i | "End"i) -> repeat
unless_statement: "Unless"i expr _CLAUSE_SEP? statement+ ("End-Unless"i | "End"i) -> unless
until_statement: "Until"i expr _CLAUSE_SEP? statement+ ("End-Until"i | "End"i) -> until
while_statement: "While"i expr _CLAUSE_SEP? statement+ ("End-While"i | "End"i) -> while

break: "Break"i
continue: "Continue"i

return: "Return"i expr?

_eq_operators: ("==" | "\u2A75" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i)                        // Unicode ⩵ (two consecutive equals signs)
_neq_operators: ("!=" | "\u2260" | "<>" | "\u00AC=" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i)  // Unicode ≠ (not eq) and ¬ (not)
_exact_eq_operators: "===" | "\u2A76" | "\u2261"                                                    // Unicode ⩶ (three consecutive equals signs) and  ≡ (identical to)
_lt_operators: ("<" | "\uFF1C" | "Is"i? "Less"i "Than"i)                                            // Unicode ＜ (fullwidth <)
_gt_operators: (">" | "\uFF1E" | "Is"i? "Greater"i "Than"i)                                         // Unicode ＞ (fullwidth >)
_le_operators: ("<=" | "\u2264" | "\u00AC>" | "!>" | "Is"i? "Not"i "Greater"i "Than"i)              // Unicode ≤ (less than or equal to) and ¬ (not)
_ge_operators: (">=" | "\u2265" | "\u00AC<" | "!<" | "Is"i? "Not"i "Less"i "Than"i)                 // Unicode ≥ (greater than or equal to) and ¬ (not)
_matches_operators: "~" | "Matches"i
_not_matches_operators: "!~" | "Not"i "~" | "Does"i "Not"i "Match"i
_matches_all_operators: "Matches"i "All"i
_contains_operators: "Contains"i
_not_contains_operators: "Does"i "Not"i "Contain"i
_contains_all_operators: "Contains"i "All"i
_is_in_operators: ("Is"i "In"i) | "\u2208"                                                          // Unicode ∈ (element of)
_not_is_in_operators: ("Is"i? "Not"i "In"i) | "\u2209"                                              // Unicode ∉ (not an element of)
_is_empty_operators: "Is"i "Empty"i
_is_not_empty_operators: "Is"i? "Not"i "Empty"i
_is_positive_operators: ("Is"i "Positive"i | "Is"i? "Not"i "Negative"i)
_is_negative_operators: ("Is"i "Negative"i | "Is"i? "Not"i "Positive"i)
_is_even_operators: ("Is"i "Even"i | "Is"i? "Not"i "Odd"i)
_is_odd_operators: ("Is"i "Odd"i | "Is"i? "Not"i "Even"i)
_is_defined_operators: "Is"i ("Defined"i | "Not"i "Undefined"i)
_is_undefined_operators: "Is"i ("Undefined"i | "Not"i "Defined"i)
_is_const_operators: "Is"i ("Constant"i | "Const"i) // TODO
_is_not_const_operators: "Is"i "Not"i ("Constant"i | "Const"i) // TODO

choose_statement: "Choose"i choose_all? _CLAUSE_SEP? choice_block* otherwise_block? ("End-Choose"i | "End"i)   -> choose
    | "Choose"i choose_all? "Using"i expr _CLAUSE_SEP? values_block* otherwise_block? ("End-Choose"i | "End"i) -> choose_using
choice_block: "When"i expr _CLAUSE_SEP? statement+
values_block: "When"i _is_empty_operators _CLAUSE_SEP? statement+                -> is_empty_block
    | "When"i _is_not_empty_operators _CLAUSE_SEP? statement+                    -> is_not_empty_block
    | "When"i _is_positive_operators _CLAUSE_SEP? statement+                     -> is_pos_block
    | "When"i _is_negative_operators _CLAUSE_SEP? statement+                     -> is_neg_block
    | "When"i _is_even_operators _CLAUSE_SEP? statement+                         -> is_even_block
    | "When"i _is_odd_operators _CLAUSE_SEP? statement+                          -> is_odd_block
    | "When"i _is_defined_operators _CLAUSE_SEP? statement+                      -> is_defined_block
    | "When"i _is_undefined_operators _CLAUSE_SEP? statement+                    -> is_undefined_block
    | "When"i _is_const_operators _CLAUSE_SEP? statement+                        -> is_const_block // TODO
    | "When"i _is_not_const_operators _CLAUSE_SEP? statement+                    -> is_not_const_block // TODO
    | "When"i expr _through expr _CLAUSE_SEP? statement+                         -> range_block
    | "When"i "Not"i expr _through expr _CLAUSE_SEP? statement+                  -> not_range_block
    // These operators work with a single value
    | "When"i (op_lt | op_gt | op_ge | op_le) expr _CLAUSE_SEP? statement+       -> ineq_block
    // This is a specialized version of "Not Equals"
    | "When"i "Not"i value_list _CLAUSE_SEP? statement+                          -> not_values_block
    // These operators work with one or more values
    // Note that the "op"s are optional, with the default being op_eq
    | "When"i (op_eq | op_ne | op_xeq | op_contains | op_not_contains | op_contains_all | op_is_in | op_not_is_in | op_matches | op_not_matches | op_matches_all)? value_list _CLAUSE_SEP? statement+
value_list: _csep_list{expr}
otherwise_block: "Otherwise"i _CLAUSE_SEP? statement+
choose_all: "All"i
_through: "Through"i | "Thru"i | "To"i
op_eq: _eq_operators
op_ne: _neq_operators
op_xeq: _exact_eq_operators
op_lt: _lt_operators
op_gt: _gt_operators
op_le: _le_operators
op_ge: _ge_operators
op_matches: _matches_operators
op_not_matches: _not_matches_operators
op_matches_all: _matches_all_operators
op_contains: _contains_operators
op_not_contains: _not_contains_operators
op_contains_all: _contains_all_operators
op_is_in: _is_in_operators
op_not_is_in: _not_is_in_operators

// simple boolean on/off, true/false
debug: "Debug"i "On"i -> debug_on
    |  "Debug"i "Off"i -> debug_off
    |  "Debug"i expr?
echo: "Echo"i "On"i -> echo_on
    | "Echo"i "Off"i -> echo_off
    | "Echo"i expr?
verbose: "Verbose"i "On"i -> verbose_on
    | "Verbose"i "Off"i -> verbose_off
    | "Verbose"i expr?

pass: ("Pass"i | "Nop"i)

accept_input: "Accept"i "Input"i ("From"i stdin)? "To"? var_name accept_input_option?
?accept_input_option: "Echo"i        -> echo
    | ("No-Echo"i | ("No"i "Echo"i)) -> no_echo
    | "Secure"i                      -> secure

sleep: "Sleep"i "For"i? expr _unit_seconds?

// NB: This is one of the parsing start points which is used for --assign.
//     It is effectively "set" without the leading statement
//     and only simple assignment can be performed.
cmd_line_assign: var_name _assignment expr -> set

_set: var_name (_assignment | SET_OP) expr
set:  "Set"i _csep_list{_set}
    | "Set"i var_name "Up"i "By"i expr   -> set_up
    | "Set"i var_name "Down"i "By"i expr -> set_down
    | "Set"i "Corresponding"i expr "In"i "Dictionary"i? var_name -> set_corresponding
SET_OP: ("+=" | "-=" | "*=" | "/=" | "%=" | "**=" | "&=" | "|=" | "^=" | "<<=" | ">>=" )
// Alternate to "Set" to get around conflicts
_assign: expr "To"i var_name
assign: "Assign"i _csep_list{_assign}

_const_set: var_name (_EQ | "Is"i) expr
const: ("Constant"i | "Const"i) _csep_list{_const_set}

add_to:     "Add"i _csep_list{expr} "To"i var_name
add_giving: "Add"i _csep_list{expr} "To"i expr "Giving"i var_name

sub_from:   "Subtract"i _csep_list{expr} "From"i var_name
sub_giving: "Subtract"i _csep_list{expr} "From"i expr "Giving"i var_name

mul_by: "Multiply"i var_name "By"i _csep_list{expr}
div_by: "Divide"i var_name "By"i _csep_list{expr}

set_key_value: ("Set-Key"i | ("Set"i "Key"i)) expr "In"i "Dictionary"i? var_name (_assignment expr)?
remove_key: ("Remove-Key"i | "Remove"i "Key"i) expr "From"i "Dictionary"i? var_name

swap: "Swap"i var_name ("With"i | "And"i) var_name

unset: "Unset"i _csep_list{var_name}

reset: "Reset"i _options_list{reset_opt}
?reset_opt: "All"i                     -> all
    |       "Args"i                    -> args
    |       "Constants"i               -> consts
    |       "Data"i                    -> data
    |       "Includes"i                -> includes
    |       "Output"i                  -> output

source: "Source"i _files_option? _csep_list{expr}
include: "@Include"i _files_option? _csep_list{expr}

load_from: "Load"i var_name ("From"i | "With"i) _file_option? expr _options_list{load_from_opts}
?load_from_opts: encoding
    | ("Type"i "Is"i?)? load_source_type
load_source_type: "CSV"i -> csv_file
    | "HCL"i -> hcl_file
    | "INI"i -> ini_file
    | "JSON"i "Object"i? -> json_object
    | "JSON"i "Object"i? "Per"i "Line"i -> json_objects
    | "Text"i -> text_file
    | "Text"i? "Lines"i -> text_lines
    | "YAML"i -> yaml_file

abort: "Abort"i _csep_list{expr}?
assert: "Assert"i expr (_CLAUSE_SEP _csep_list{expr})?

print:  "Print"i _csep_list{expr} print_channel? _options_list{print_option}
printf: "Printf"i _csep_list{expr} print_channel? _options_list{printf_option}
?print_channel: "To"i (stderr | stdout) // -> stderr or stdout
    | "As"i "Markdown"i                     -> markdown
?print_sep_opt: (("Field"i "Separator"i) | "OFS"i) option_value  -> ofs
    |           (("Record"i "Separator"i) | "ORS"i) option_value -> ors
?print_flush_opt: ("Flush"i) option_value?                       -> flush
    |             ("No-Flush"i) option_value?                    -> no_flush
?print_option: print_sep_opt | print_flush_opt
?printf_option: print_flush_opt

exhibit: "Exhibit"i "*" // exhibit all
    |    "Exhibit"i var_name (_SEP? var_name)*

log: "Log"i log_level _csep_list{expr}
   | "Log"i "Level"i log_level -> log_setlevel
?log_level: "Debug"i -> debug
    | "Info"i -> info
    | ("Warn"i | "Warning"i) -> warn
    | "Error"i -> error

open: "Open"i (stderr | stdout | stdin) _file_option? expr _options_list{open_option}
?open_option: encoding | open_mode
?open_mode: ("Append"i | "Extend"i) -> a
    |       "Overwrite"i            -> w
    |       "No"i "Overwrite"i      -> x
    |       "Read"i                 -> r
close: "Close"i (stderr | stdout | stdin) _file_option?

zip: ("Create-Zip"i | "Create"i "Zip"i) _file_option? expr _options_list{zip_option}
?zip_option: open_mode
    | "Comment"i option_value -> comment
    | "Paths"i -> keep_paths
    | "Junk"i "Paths"i -> junk_paths
    | "Include"i expr -> include
    | "Exclude"i expr -> exclude

exit: "Exit"i expr?

sort: "Sort"i sort_source sort_keys? unique_clause? sort_giving?
sort_source: sort_obj -> source
sort_giving: "Giving"i sort_obj -> target
?sort_obj: _file_option expr (_SEP? load_from_opts)* -> file
    | var_name -> var
sort_keys: ("On"i | "By"i) _csep_list{sort_key} -> keys
sort_key: sort_dir? "Key"i? expr -> key
?sort_dir: ("Ascending"i | "Asc"i) -> sort_asc
    | ("Descending"i | "Des"i) -> sort_des
unique_clause: "Unique"i ("On"i _csep_list{expr})? -> unique

list_append: "Append"i list_all? expr "To"i "List"i? var_name
list_prepend: "Prepend"i list_all? expr "To"i "List"i? var_name
list_insert: "Insert"i list_all? expr "Into"i "List"i? var_name "At"i ("Position"i | "Index"i)? expr
list_remove: "Remove"i ("Position"i | "Index"i)? expr "From"i "List"i? var_name giving_clause?
list_remove_first: "Remove"i "First"i "Item"i? "From"i "List"i? var_name giving_clause?
list_remove_last: "Remove"i "Last"i "Item"i? "From"i "List"i? var_name giving_clause?
list_replace: "Replace"i ("Position"i | "Index"i)? expr "In"i "List"i? var_name "With"i expr giving_clause?
list_all: "All"i

_records: ("Record"i | "Records"i)
_columns: ("Column"i | "Columns"i)

select: "Select"i _records? select_outputs from_clause where_clause? product_clause? limit_clause? for_clause? into_clause?

?select_outputs: _csep_list{select_output} _SEP?
select_output: "*"   -> output_all
    | expr as_clause -> output_as
    | expr           -> output
?as_clause: "As"i expr

?from_clause: "From"i (expr_from | file_from)
expr_from: expr as_clause?
file_from: _file_option expr (_SEP? (load_from_opts | as_clause))*

where_clause: "Where"i _csep_list{expr}

product_clause: "Cartesian"i? "Product"i "Of"i? _columns? product_cols
product_cols: ("All"i | "*") -> product_all
    |         _csep_list{expr}

limit_clause: "Limit"i "Input"i option_value _records? (_SEP? "Offset"i option_value)? -> limit_input
    |         "Limit"i          option_value _records? (_SEP? "Offset"i option_value)? -> limit_output

?for_clause: "For"i (for_json | for_csv | for_markdown | for_text | for_template)

into_clause: "Into"i var_name
    | "Into"i (stdout | stderr)
    | "Into"i _file_option expr _options_list{open_option}

for_json: "JSON"i _options_list{json_option}
?json_option: exclude_nulls | include_nulls
    | "Root"i option_value?                        -> root
    | "Indent"i option_value?                      -> indent
    | "Compact"i option_value?                     -> compact
    | "Array"i "Wrapper"i option_value?            -> array_wrapper
    | ("Sort"i "Keys"i? | "Sorted"i) option_value? -> sort_keys

for_csv: "CSV"i _options_list{csv_option}
?csv_option: include_headers | exclude_headers
    | "Delimiter"i _character_option? option_value -> delimiter
    | "Quote"i _character_option option_value      -> quotechar
    | "Escape"i _character_option option_value     -> escapechar
    | "Line"i "Terminator"i option_value           -> lineterminator
    | "Quoting"i "Style"i option_value             -> quoting
_character_option: "Char"i | "Character"i

for_markdown: "MarkDown"i _options_list{markdown_option}
?markdown_option: include_headers | exclude_headers

for_template: template_type? ("Template"i | "Jinja"i | "Jinja2"i) (template_filename | "Default"i)? _options_list{template_option}
?template_type: "Record"i -> record
    |           "Batch"i  -> batch
template_filename: _file_option? expr
?template_option: include_headers | exclude_headers
    | "Auto"i "Escape"i option_value?                   -> auto_escape
    | "Trim"i "Blocks"i? option_value?                  -> trim_blocks
    | "Left"i "Strip"i "Blocks"i? option_value?         -> lstrip_blocks
    | "Keep"i "Last"i "Newline"i option_value?          -> keep_last_newline
    | "Chain"i "Undefined"i "Variables"i? option_value? -> chain_undefined

for_text: "Text"i _options_list{for_text_option}
?for_text_option: include_headers | exclude_headers
    | exclude_nulls | include_nulls
    | "Field"i "Separator"i option_value  -> field_sep
    | "Header"i "Separator"i option_value -> header_sep
    | "Record"i "Separator"i option_value -> record_sep

include_headers: "Include"i _headers_option option_value?
exclude_headers: "Exclude"i _headers_option option_value?
exclude_nulls: "Exclude"i _null_values_option option_value?
include_nulls: "Include"i _null_values_option option_value?

?expr: ternary | and_expr

// NB: Python style has multiple grammar issues
//     and while we diferentiate the style by name,
//     it is unlikely that anything other than a
//     'C'/Java style will be supported.
ternary: expr "?" expr _CLAUSE_SEP expr -> c_ternary

?and_expr: or_expr
    | or_expr (("&&" | "\u2227" | "And"i) or_expr)+ -> and_op // Unicode ∧ (conjunction)

?or_expr: expr2
    | expr2 (("||" | "\u2228" | "Or"i) expr2)+ -> or_op // Unicode ∨ (disjunction)

// Flattening operations out here allows the parse tree to hold
// the operation type explicitly instead of a generic "OP" where
// we need to deal with aliases.
// NB: subscripts cannot be used with var_name, thus they
//     cannot be used when invoking user functions
?expr2: atom
    # Reserved: not working
    #| (var_name ":=" expr)                       -> assignment_expr
    | "(" expr ")"
    // must be expr2 not expr else it binds across and/or
    | ("!" | "\uFF01" | "\u00AC") expr2 -> unary_not // Unicode ！(fullwidth excl) and ¬ (logical not)
    | expr2 "." dotfunction                            -> dotfunction_call
    | expr2 "." NAME                                   -> deref
    | expr2 ("[" expr "]")+                            -> subscript
    | expr2 "." "@" var_name "(" _csep_list{expr}? ")" -> invoke_func_inline
    | "@" var_name "(" _csep_list{expr}? ")"           -> invoke_func
    | function                                         -> function_call
    | expr2 _is_negative_operators                     -> is_negative_op
    | expr2 _is_positive_operators                     -> is_positive_op
    | expr2 _is_even_operators                         -> is_even_op
    | expr2 _is_odd_operators                          -> is_odd_op
    | expr2 _is_defined_operators                      -> is_defined_op
    | expr2 _is_undefined_operators                    -> is_undefined_op
    | expr2 _is_const_operators                        -> is_const_op // TODO
    | expr2 _is_not_const_operators                    -> is_not_const_op // TODO
    | expr2 _is_empty_operators                        -> is_empty_op
    | expr2 _is_not_empty_operators                    -> is_not_empty_op
    // Binary operators
    | expr2 ("+" | "\uFF0B") expr2                     -> add_op // Unicode ＋ (fullwidth plus)
    | expr2 ("-" | "\u2212" | "\uFF0D") expr2          -> sub_op // Unicode − (minus sign) and － (fullwidth minus)
    | expr2 ("*" | "\u00D7") expr2                     -> mul_op // Unicode × (multiplication)
    | expr2 ("/" | "\u00F7") expr2                     -> div_op // Unicode ÷ (division)
    | expr2 "%" expr2                                  -> mod_op
    | expr2 "**" expr2                                 -> pow_op
    | expr2 "&" expr2                                  -> bit_and_op
    | expr2 "|" expr2                                  -> bit_or_op
    | expr2 "^" expr2                                  -> bit_xor_op
    | expr2 "<<" expr2                                 -> shl_op
    | expr2 ">>" expr2                                 -> shr_op
    // Relation operators bools
    | expr2 _exact_eq_operators expr2                  -> exact_eq_op
    | expr2 _eq_operators expr2                        -> eq_op
    | expr2 _neq_operators expr2                       -> neq_op
    | expr2 _lt_operators expr2                        -> lt_op
    | expr2 _gt_operators expr2                        -> gt_op
    | expr2 _le_operators expr2                        -> le_op
    | expr2 _ge_operators expr2                        -> ge_op
    | expr2 _is_in_operators expr2                     -> in_op
    | expr2 _not_is_in_operators expr2                 -> not_in_op
    | expr2 _contains_operators expr2                  -> contains_op
    | expr2 _not_contains_operators expr2              -> not_contains_op
    | expr2 _contains_all_operators expr2              -> contains_all_op
    | expr2 _matches_operators expr2                   -> matches_op
    | expr2 _not_matches_operators expr2               -> not_matches_op
    | expr2 _matches_all_operators expr2               -> matches_all_op
    // Misc operators
    | "\u2308" expr "\u2309"                            -> ceil_op      // Unicode ceiling ⌈ x ⌉
    | "\u230A" expr "\u230B"                            -> floor_op     // Unicode floor ⌊ x ⌋
    | expr2 SUPERSCRIPT_FLOAT                           -> pow_op
    // NB: neither of the following work with trailing commas if you use the template
    | "[" (expr (_SEP expr)*)? _SEP? "]"                -> array        // [], [x], [x,y], [x,y,]
    | "{" (_dict_entry (_SEP _dict_entry)*)? _SEP? "}"  -> dict         // {}, {x:y}, {a:b,x:y}, {a:b,x:y,}

_dict_entry: expr _CLAUSE_SEP expr // key and value

?atom: ("None"i  | "\u2205" | "Null"i) -> vnone         // Unicode ∅ (Empty set)
    // Boolean constants
    | "True"i               -> vtrue
    | "False"i              -> vfalse
    // Numeric figurative constants
    | "Nan"i                -> vnan
    | "Zero"i               -> vzero                    // becomes int 0
    | ("Inf"i   | "\u221E") -> vinf                     // Unicode ∞ (infinity)
    // Character figurative constants
    // These are here to support structured text formats (CSV, JSON, et al)
    // and is intentionally NOT a "punctuation catalog"
    | "Colon"i              -> vcolon                   // becomes ':'
    | "Comma"i              -> vcomma                   // becomes ','
    | "Newline"i            -> vnewline                 // becomes '\n'
    | "Period"i             -> vperiod                  // becomes '.'
    | "Quote"i              -> vquote                   // becomes '"'
    | "Space"i              -> vspace                   // becomes " "
    | "Tab"i                -> vtab                     // becomes '\t'
    | "Escape"i             -> vescape                  // becomes '\x1b'
    | "Backslash"i          -> vbackslash               // becomes '\\'
    // Values that closely follow Python and other lanuages
    | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | DEC_NUMBER // becomes INT at runtime
    | FLOAT_NUMBER                                      // becomes FLOAT at runtime
    | REGEX                                             // becomes Pattern at runtime
    | STRING
    | NAME -> var_ref

var_name: NAME ("." NAME)*

{EXTN_GRAMMAR}

{FUNCTIONS}

// Regex contents:
//   * Cannot be empty (ie "r//" : that's a comment!)
//   * \[/\] : an escaped "/" or "\"
//   * [^/, [/, and /] : "/" escaped by a character group (but only first/last)
//   * [^\x00-\x1f\x7f\/] : not a control character or a "/"
//   * flags: optional, must be lowercase and immediately follow the closing "/"
//   * locale flag not supported because it only works with bytes
//   * unicode flag not supported because it is redundant
//   * template flag not supported as obsolete
REGEX.2: /r\/(?:(?:\\[\/\\])|(?:\[^\/)|(?:\[\/)|(?:\/\])|(?:[^\x00-\x1f\x7f\/]))+\/[adimsx]*/

// modified versions of python.STRING/LONG_STRING : removed the [f]
// NB: we don't enforce validity of prefixes here
_VSTRING: /[BRbr]*("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/
_LONG_VSTRING: /[BRbr]*(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?''')/s
// Allow typographic quotes from C/P sources, but fix them up internally
_MS_STRING: /[BRbr]*(\u201C.*?(?<!\\)(\\\\)*?\u201D|\u2018.*?(?<!\\)(\\\\)*?\u2019)/
STRING: _VSTRING | _LONG_VSTRING | _MS_STRING

SH_COMMENT.4: /#[^\n]*/
CPP_COMMENT.4: /\/\/[^\n]*/
C_COMMENT.4: "/*" /(.|\n)*?/ "*/"

%import common.WS
%ignore WS
%ignore SH_COMMENT
%ignore C_COMMENT
%ignore CPP_COMMENT
