//----------------------------------------------------------
// VGR - A DSL for scripting reports
//----------------------------------------------------------

// These are functionally named, but as terminals,
// you should use them anywhere the characters are required.
_CLAUSE_SEP: ":"
_SEP: ","

// Numeric values
// NB: octal and binary regexs are shorter than the length
//     of the decimal regex, so we need to boost their
//     priorities so the former's leading zero doesn't get
//     prematurely matched by the latter.
HEX_NUMBER.2: /0[xX](?:_?[0-9a-fA-F])+/
OCT_NUMBER.2: /0[oO](?:_?[0-7])+/
BIN_NUMBER.2: /0[bB](?:_?[01])+/
DEC_NUMBER: /-?[0-9](?:_?[0-9])*/
_SPECIAL_DEC: /[0-9](?:_?[0-9])*/
_EXP_PART: /[eE][+-][0-9](?:_?[0-9])*/
// NB: slight difference from Python as floats can't end with a "."
_DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC
FLOAT_NUMBER: "-"? (_SPECIAL_DEC _EXP_PART | _DECIMAL _EXP_PART?)

// This becomes either a FLOAT or INT (when no decimal referenced) at runtime
SUPERSCRIPT_FLOAT: /⁽[⁺⁻]?(?:[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?|·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)⁾|[⁺⁻]?(?:[⁰¹²³⁴⁵⁶⁷⁸⁹]+(·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)?|·[⁰¹²³⁴⁵⁶⁷⁸⁹]+)/

// NB: This pattern is very long and tends to win out over keyword tokens
//     If it's priority is set lower, you need to adjust the priority on
//     ALL tokens
NAME: /{VAR_NAME}/

//----------------------------------------------------------
_EQ: "="
_assignment: _EQ | "To"i
_file_option: "File"i
_files_option: "File"i | "Files"i
_headers_option: "Header"i | "Headers"i
_null_values_option: "Nulls"i | "Null"i "Values"i
_unit_seconds: "Second"i | "Seconds"i
//----------------------------------------------------------

//----------------------------------------------------------
// Templates
//----------------------------------------------------------
// Comma separated list
_csep_list{t_type}: t_type (_SEP t_type)*
// Optional-comma separated list (the comma is optional
_ocsep_list{t_type}: t_type (_SEP? t_type)*
//----------------------------------------------------------


opt_statements: statement*

// NB: this is the only place where we have to reference the optional statement ender
?statement: (simple_statement | select | control_statements | def_statements {EXTN_STATEMENTS}) ";"?
    | ";" -> pass // blank statement synonymous with "pass"

?simple_statement: assert
    | break
    | call
    | close
    | continue
    | debug
    | declare
    | echo
    | exit
    | include
    | list_append
    | list_insert
    | list_prepend
    | list_remove
    | list_remove_first
    | list_remove_last
    | list_replace
    | load_from
    | log
    | open
    | pass
    | print
    | printf
    | reset
    | return
    | set
    | sleep
    | sort
    | source
    | swap
    | unset
    | verbose
    | zip

?control_statements: block_statement
    | choose_statement
    | foreach_statement
    | if_statement
    | repeat_statement
    | unless_statement
    | until_statement
    | while_statement
    | forever_loop

// Some common patterns
?giving_clause: "Giving"i var_name
?option_value: "Is"i? expr
stderr: ("Error"i | "stderr"i)
stdout: ("Output"i | "stdout"i | "sysprint"i)
stdin: ("Input"i | "stdin"i | "sysin"i)
encoding: "Encoding"i option_value

block_statement: "Begin"i _CLAUSE_SEP? statement+ "End"i -> block
call: "Call"i "Function"i? var_name ("(" _csep_list{expr}? ")")?
    | "Call"i "Function"i? var_name ("(" _csep_list{expr}? ")")? giving_clause -> call_giving
    | "Call"i "Function"i? var_name "Using"i _csep_list{expr}
    | "Call"i "Function"i? var_name "Using"i _csep_list{expr} giving_clause -> call_giving
declare: "Declare"i _csep_list{var_name}
    | "Declare"i _csep_list{var_name} "As"i? "Local"i  -> declare_local
    | "Declare"i _csep_list{var_name} "As"i? "Global"i -> declare_global
def_statements: "Define"i? "Function"i var_name def_params? _CLAUSE_SEP? def_body ("End-Function"i | "End"i) -> def_function
// NB: doesn't work with template; probably should be changed to use var_name anyway
def_params: "(" (NAME (_SEP NAME)*)? ")" -> params
def_body: statement+ -> body
// Note: this combines BASIC-like syntax (For Each) and VGR (ForEach), now somewhat deprecated
foreach_statement: ("For"i "Each"i | "ForEach"i) var_name "In"i expr _CLAUSE_SEP? statement+ ("Next"i | "End-For"i | "End"i) -> foreach
forever_loop: "Do"i "Forever"i _CLAUSE_SEP? statement+ ("End-Do"i | "End"i) -> forever

// The addition of the optional "Then" allows a BASIC-like If syntax usage
if_statement: "If"i expr ("Then"i | _CLAUSE_SEP)? statement+ else_clause? ("End-If"i | "End"i) -> if
else_clause: "Else"i _CLAUSE_SEP? statement+ -> else

repeat_statement: "Repeat"i expr ("Time"i | "Times"i)? _CLAUSE_SEP? statement+ ("End-Repeat"i | "End"i) -> repeat
unless_statement: "Unless"i expr _CLAUSE_SEP? statement+ ("End-Unless"i | "End"i) -> unless
until_statement: "Until"i expr _CLAUSE_SEP? statement+ ("End-Until"i | "End"i) -> until
while_statement: "While"i expr _CLAUSE_SEP? statement+ ("End-While"i | "End"i | "Loop"i) -> while

break: "Break"i
continue: "Continue"i
return: "Return"i expr?

// NB: Unicode alternates exist here and elsewhere only for logical or mathematical operations and constants, not textual ones.

op_eq: ("==" | "\u2175" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i)                       // Unicode ⩵ (two consecutive equals signs)
op_ne: ("!=" | "\u2260" | "<>" | "\u00AC=" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i ) // Unicode ≠ (not eq) and ¬ (not)
// NB: intentionally "not greater than or equal to" et al
op_lt: ("<" | "\uFF1C" | "Less"i "Than"i)                                                  // Unicode ＜ (fullwidth <)
op_gt: (">" | "\uFF1E" | "Greater"i "Than"i)                                               // Unicode ＞ (fullwidth >)
op_le: ("<=" | "\u2264" | "\u00AC>" | "!>") | ("Not"i op_gt)                               // Unicode ≤ (less than or equal to) and ¬ (not)
op_ge: (">=" | "\u2265" | "\u00AC<" | "!<") | ("Not"i op_lt)                               // Unicode ≥ (greater than or equal to) and ¬ (not)
op_contains: "Contains"i
op_not_contains: ("Not"i op_contains | "Does"i "Not"i "Contain"i)
op_matches: "~" | "Matches"i
op_not_matches: ("!~" | "Not"i op_matches | "Does"i "Not"i "Match"i)
op_matches_all: "Matches"i "All"i
op_imatches: ("~*" | "IMatches"i)
op_not_imatches: ("!~*" | "Not"i op_imatches | "Does"i "Not"i "IMatch"i)

choose_statement: "Choose"i choose_all? _CLAUSE_SEP? choice_block+ otherwise_block? ("End-Choose"i | "End"i) -> choose
    | "Choose"i choose_all? "Using"i expr _CLAUSE_SEP? values_block+ otherwise_block? ("End-Choose"i | "End"i) -> choose_using
choose_all: "All"i
choice_block: "When"i expr _CLAUSE_SEP? statement+
values_block: "When"i "Is"i? "Empty"i _CLAUSE_SEP? statement+ -> is_empty_block
    | "When"i "Is"i? "Not"i "Empty"i _CLAUSE_SEP? statement+ -> is_not_empty_block
    | "When"i "Is"i? ("Positive"i | "Not"i "Negative"i) _CLAUSE_SEP? statement+ -> is_pos_block
    | "When"i "Is"i? ("Negative"i | "Not"i "Positive"i) _CLAUSE_SEP? statement+ -> is_neg_block
    | "When"i "Is"i? ("Even"i | "Not"i "Odd"i) _CLAUSE_SEP? statement+ -> is_even_block
    | "When"i "Is"i? ("Odd"i | "Not"i "Even"i) _CLAUSE_SEP? statement+ -> is_odd_block
    | "When"i value_list _CLAUSE_SEP? statement+
    | "When"i "Not"i value_list _CLAUSE_SEP? statement+ -> not_values_block
    | "When"i expr ("Through"i | "Thru"i | "To"i) expr _CLAUSE_SEP? statement+ -> range_block
    | "When"i "Not"i expr ("Through"i | "Thru"i | "To"i) expr _CLAUSE_SEP? statement+ -> not_range_block
    | "When"i (op_lt | op_gt | op_ge | op_le) expr _CLAUSE_SEP? statement+ -> ineq_block
    | "When"i (op_eq | op_ne | op_contains | op_not_contains | op_matches | op_not_matches | op_matches_all) value_list _CLAUSE_SEP? statement+
value_list: _csep_list{expr}
otherwise_block: "Otherwise"i _CLAUSE_SEP? statement+

// simple boolean on/off, true/false
// these are "proper statements" as they control the behavior of other statements
debug: "Debug"i expr?
echo: "Echo"i expr?
verbose: "Verbose"i expr?

pass: ("Pass"i | "Nop"i)

sleep: "Sleep"i "For"i? expr _unit_seconds?

// NB: This is one of the parsing start points which is used for --assign.
//     It is effectively "set" without the leading statement
//     and only simple assignment can be performed.
cmd_line_assign: var_name _assignment expr -> set

// TODO: the arrow functions should move to "Define Function"
set:  "Set"i? var_name _assignment expr
    | "Set"i? var_name IN_PLACE_OP expr
    | "Set"i? var_name _assignment? def_params? _function_arrow expr -> set_arrow
    | "Set"i? var_name _assignment? def_params? _function_arrow "Compile"i "(" expr ")" -> compile_arrow
IN_PLACE_OP: ("+=" | "-=" | "*=" | "/=" | "%=" | "**=" | "&=" | "|=" | "^=" | "<<=" | ">>=" )
_function_arrow: "->" | "=>" | "\u2192"

swap: "Swap"i var_name ("With"i | "And"i) var_name

unset: "Unset"i _csep_list{var_name}

reset: "Reset"i _ocsep_list{reset_opt}?
?reset_opt: "All"i               -> all
    | "Data"i                    -> data
    | "Args"i                    -> args
    | "Output"i                  -> output
    | ("Include"i | "Includes"i) -> includes

source: "Source"i _files_option? _csep_list{expr}
include: "@Include"i _files_option? _csep_list{expr}

load_from: "Load"i var_name ("From"i | "With"i) _file_option? expr (_SEP? _ocsep_list{load_from_opts})?
?load_from_opts: encoding
    | ("Type"i "Is"i?)? load_source_type
load_source_type: "CSV"i -> csv_file
    | "HCL"i -> hcl_file
    | "INI"i -> ini_file
    | "JSON"i "Object"i? -> json_object
    | "JSON"i "Object"i? "Per"i "Line"i -> json_objects
    | "Text"i -> text_file
    | "Text"i? "Lines"i -> text_lines
    | "YAML"i -> yaml_file

assert: "Assert"i expr (_CLAUSE_SEP _csep_list{expr})?

print: "Print"i print_channel? _csep_list{expr}
printf: "Printf"i print_channel? _csep_list{expr}
?print_channel: ("On"i | "To"i)? (stderr | stdout)
    | "As"i? "Markdown"i -> markdown

log: "Log"i log_level _csep_list{expr}
   | "Log"i "Level"i log_level -> log_setlevel
?log_level: "Debug"i -> debug
    | "Info"i -> info
    | ("Warn"i | "Warning"i) -> warn
    | "Error"i -> error

open: "Open"i (stderr | stdout | stdin) _file_option? expr (_SEP? _ocsep_list{open_option})?
?open_option: encoding
    | ("Append"i | "Extend"i | "a"i) -> a
    | ("Overwrite"i | "w"i)          -> w
    | ("No"i "Overwrite"i | "x"i)    -> x
    | ("Read"i | "r"i)               -> r
close: "Close"i (stderr | stdout | stdin) _file_option?

zip: "Create"i "Zip"i _file_option? expr (_SEP? _ocsep_list{zip_option})?
?zip_option: "Comment"i option_value -> comment
    | "Include"i "Is"i? expr+ -> include
    | "Exclude"i "Is"i? expr+ -> exclude

exit: "Exit"i expr?

sort: "Sort"i sort_source sort_keys? unique_clause? sort_giving?
sort_source: sort_obj -> source
sort_giving: "Giving"i sort_obj -> target
?sort_obj: _file_option expr (_SEP? load_from_opts)* -> file
    | var_name -> var
sort_keys: ("On"i | "By"i) _csep_list{sort_key} -> keys
sort_key: sort_dir? "Key"i? expr -> key
?sort_dir: ("Ascending"i | "Asc"i) -> sort_asc
    | ("Descending"i | "Des"i) -> sort_des
unique_clause: "Unique"i ("On"i _csep_list{expr})? -> unique

list_append: "Append"i list_all? expr "To"i "List"i? var_name
list_prepend: "Prepend"i list_all? expr "To"i "List"i? var_name
list_insert: "Insert"i list_all? expr "Into"i "List"i? var_name "At"i ("Position"i | "Index"i)? expr
list_remove: "Remove"i ("Position"i | "Index"i)? expr "From"i "List"i? var_name giving_clause?
list_remove_first: "Remove"i "First"i "Item"i? "From"i "List"i? var_name giving_clause?
list_remove_last: "Remove"i "Last"i "Item"i? "From"i "List"i? var_name giving_clause?
list_replace: "Replace"i ("Position"i | "Index"i)? expr "In"i "List"i? var_name "With"i expr giving_clause?
list_all: "All"i

select: "Select"i select_outputs from_clause where_clause? product_clause? limit_clause? for_clause? into_clause?

?select_outputs: _csep_list{select_output} _SEP?

select_output: "*"    -> output_all
    | expr "As"i expr -> output_as
    | expr            -> output

?from_clause: "From"i (expr_from | file_from)
expr_from: expr as_clause?
file_from: _file_option expr (_SEP? (load_from_opts | as_clause))*
?as_clause: "As"i expr

into_clause: "Into"i var_name
    | "Into"i (stdout | stderr)
    | "Into"i _file_option expr (_SEP? _ocsep_list{open_option})?

where_clause: "Where"i _csep_list{expr}

?for_clause: "For"i (for_json | for_csv | for_markdown | for_text | for_template)

for_json: "JSON"i (_SEP? _ocsep_list{json_option})?
?json_option: exclude_nulls | include_nulls
    | "Root"i option_value? -> root
    | "Indent"i option_value? -> indent
    | "Compact"i option_value? -> compact
    | "With"i? "Array"i "Wrapper"i option_value? -> array_wrapper
    | ("Without"i | "No"i) "Array"i "Wrapper"i option_value? -> no_array_wrapper
    | ("Sort"i "Keys"i? | "Sorted"i) option_value? -> sort_keys

for_csv: "CSV"i (_SEP? _ocsep_list{csv_option})?
?csv_option: include_headers | exclude_headers
    | "Delimiter"i option_value -> delimiter
    | "Quote"i ("Char"i | "Character"i) option_value -> quotechar
    | "Escape"i ("Char"i | "Character"i) option_value -> escapechar
    | "Line"i ("Ender"i | "Terminator"i) option_value -> lineterminator
    | "Quote"i "Is"i? CSV_QUOTE_TYPE -> quoting
CSV_QUOTE_TYPE: "Minimal"i | "All"i | "Nonnumeric"i | "None"i

for_markdown: "MarkDown"i (_SEP? _ocsep_list{markdown_option})?
?markdown_option: include_headers | exclude_headers

for_template: template_type? ("Template"i | "Jinja"i | "Jinja2"i) (template_filename | "Default"i)? (_SEP? _ocsep_list{template_option}*)?
?template_type: "Record"i -> record
    | "Batch"i -> batch
template_filename: _file_option? expr
?template_option: include_headers | exclude_headers
    | "Auto"i "Escape"i option_value? -> auto_escape
    | "Trim"i "Blocks"i? option_value? -> trim_blocks
    | "Left"i "Strip"i "Blocks"i? option_value? -> lstrip_blocks
    | "Keep"i "Last"i "Newline"i option_value? -> keep_last_newline
    | "Chain"i "Undefined"i "Variables"i? option_value? -> chain_undefined

for_text: "Text"i (_SEP? _ocsep_list{for_text_option})?
?for_text_option: include_headers | exclude_headers
    | exclude_nulls | include_nulls
    | "Field"i "Separator"i option_value -> field_sep
    | "Header"i "Separator"i option_value -> header_sep
    | "Record"i "Separator"i option_value -> record_sep

include_headers: "Include"i _headers_option option_value?
exclude_headers: "Exclude"i _headers_option option_value?
exclude_nulls: "Exclude"i _null_values_option option_value?
include_nulls: "Include"i _null_values_option option_value?

// Either LIMIT <number> (OFFSET <number>)?
// or FETCH FIRST <number> ROWS ONLY
limit_clause: _limit_offset | _fetch_first
_limit_offset: "Limit"i option_value (_SEP? "Offset"i option_value)?
_fetch_first: "Fetch"i "First"i expr "Rows"i "Only"i

product_clause: "Cartesian"i? "Product"i product_cols
product_cols: "All"i -> all
    | "None"i -> none
    | _csep_list{col_spec}
?col_spec: DEC_NUMBER // One based
    | NAME
    | STRING
// TODO: option to say before or after limits

?expr: ternary | and_expr

ternary: expr "?" expr _CLAUSE_SEP expr -> c_ternary
//    | expr "If"i expr "Else"i expr -> py_ternary // TODO collision with "real" If statement, but only when capitalized?
// When LC, it works, but if (true if 5<7 else false)  print "a" else print "b" end doesn't parse

?and_expr: or_expr
    | or_expr (("&&" | "\u2227" | "And"i) or_expr)+ -> and_op // Unicode ∧ (conjunction)

?or_expr: expr2
    | expr2 (("||" | "\u2228" | "Or"i) expr2)+ -> or_op // Unicode ∨ (disjunction)

// Flattening operations out here allows the parse tree to hold
// the operation type explicitly instead of a generic "OP" where
// we need to deal with aliases.
// See previous comment on use of Unicode alternates
?expr2: atom
    | "(" expr ")"
    // must be expr2 not expr else it binds across and/or
    | ("!" | "\uFF01" | "\u00AC") expr2 -> unary_not // Unicode ！(fullwidth excl) and ¬ (logical not)
    | expr2 "." dotfunction                            -> dotfunction_call
    | expr2 "." NAME                                   -> deref
    | expr2 "." "@" var_name "(" _csep_list{expr}? ")" -> invoke_func_inline
    | "@" var_name "(" _csep_list{expr}? ")"           -> invoke_func
    | function                                         -> function_call
    | expr2 "Is"i ("Negative"i | "Not"i "Positive"i)   -> is_negative_op
    | expr2 "Is"i ("Positive"i | "Not"i "Negative"i)   -> is_positive_op
    | expr2 "Is"i ("Even"i | "Not"i "Odd"i)            -> is_even_op
    | expr2 "Is"i ("Odd"i | "Not"i "Even"i)            -> is_odd_op
    | expr2 "Is"i ("Defined"i | "Not"i "Undefined"i)   -> is_defined
    | expr2 "Is"i ("Undefined"i | "Not"i "Defined"i)   -> is_undefined
    // Polymorphic operations than *could* be chained
    | expr2 ("+" | "\uFF0B") expr2                     -> add_op // Unicode ＋ (fullwidth plus)
    | expr2 ("-" | "\u2212" | "\uFF0D") expr2          -> sub_op // Unicode − (minus sign) and － (fullwidth minus)
    | expr2 ("*" | "\u00D7") expr2                     -> mul_op // Unicode × (multiplication)
    | expr2 ("/" | "\u00F7") expr2                     -> div_op // Unicode ÷ (division)
    | expr2 "%" expr2                                  -> mod_op
    | expr2 "**" expr2                                 -> pow_op
    | expr2 "&" expr2                                  -> bit_and_op
    | expr2 "|" expr2                                  -> bit_or_op
    | expr2 "^" expr2                                  -> bit_xor_op
    | expr2 "<<" expr2                                 -> shl_op
    | expr2 ">>" expr2                                 -> shr_op
    // Return bools, typically not "chained"
    | expr2 ("===") expr2                              -> exact_eq_op
    | expr2 ("==" | "\u2175" | "Equals"i | "Is"i | "Is"i? "Equal"i "To"i) expr2 -> eq_op // Unicode ⩵ (two consecutive equals signs)
    | expr2 ("!=" | "\u2260" | "<>" | "\u00AC=" | "Is"i "Not"i | "Is"i? "Not"i "Equal"i "To"i ) expr2 -> neq_op // Unicode ≠ (not eq) and ¬ (not)
    | expr2 ("<" | "\uFF1C" | "Is"i? "Less"i "Than"i) expr2 -> lt_op // Unicode ＜ (fullwidth <)
    | expr2 (">" | "\uFF1E" | "Is"i? "Greater"i "Than"i) expr2 -> gt_op // Unicode ＞ (fullwidth >)
    | expr2 ("<=" | "\u2264" | "\u00AC>" | "!>" | "Is"i? "Not"i "Greater"i "Than"i) expr2 -> le_op // Unicode ≤ (less than or equal to) and ¬ (not)
    | expr2 (">=" | "\u2265" | "\u00AC<" | "!<" | "Is"i? "Not"i "Less"i "Than"i) expr2 -> ge_op // Unicode ≥ (greater than or equal to) and ¬ (not)
    | expr2 (("Is"i "In"i) | "\u2208") expr2 -> in_op // Unicode ∈ (element of)
    | expr2 (("Is"i "Not"i "In"i) | "\u2209") expr2     -> not_in_op // Unicode ∉ (not an element of)
    | expr2 "Contains"i expr2                           -> contains_op
    | expr2 "Contains"i "All"i expr2                    -> contains_all_op
    | expr2 op_matches expr2                            -> matches_op
    | expr2 op_matches_all expr2                        -> matches_all_op
    | expr2 op_imatches expr2                           -> imatches_op
    | expr2 op_not_matches expr2                        -> not_matches_op
    | expr2 op_not_imatches expr2                       -> not_imatches_op
    // Misc operations
    | "\u2308" expr "\u2309"                            -> ceil_op      // Unicode ceiling ⌈ x ⌉
    | "\u230A" expr "\u230B"                            -> floor_op     // Unicode floor ⌊ x ⌋
    | expr2 SUPERSCRIPT_FLOAT                           -> pow_op
    // NB: neither of the following work with trailing commas if you use the template
    | "[" (expr (_SEP expr)*)? _SEP? "]"                -> array        // [], [x], [x,y], [x,y,]
    | "{" (_dict_entry (_SEP _dict_entry)*)? _SEP? "}"  -> dict         // {}, {x:y}, {a:b,x:y}, {a:b,x:y,}

_dict_entry: expr _CLAUSE_SEP expr // key and value

?atom: ("None"i  | "\u2205" | "Null"i) -> vnone         // Unicode ∅ (Empty set)
    // Boolean constants
    | ("True"i  | "\u22A4") -> vtrue                    // Unicode ⊤ (top)
    | ("False"i | "\u22A5") -> vfalse                   // Unicode ⊥ (bottom)
    // Figurative constants: where COBOL "inspired" only the singular version is used
    // Numeric figurative constants
    | "Nan"i                -> vnan
    | "Zero"i               -> vzero                    // becomes int 0
    | ("Inf"i   | "\u221E") -> vinf                     // Unicode ∞ (infinity)
    // Character figurative constants
    // These are here to support structured text formats (CSV, JSON, et al)
    // and is intentionally NOT a "punctuation catalog"
    | "Colon"i              -> vcolon                   // becomes ':'
    | "Comma"i              -> vcomma                   // becomes ','
    | "Newline"i            -> vnewline                 // becomes '\n'
    | "Period"i             -> vperiod                  // becomes '.'
    | "Quote"i              -> vquote                   // becomes '"'
    | "Space"i              -> vspace                   // becomes " "
    | "Tab"i                -> vtab                     // becomes '\t'
    | "Escape"i             -> vescape                  // becomes '\x1b'
    | "Backslash"i          -> vbackslash               // becomes '\\'
    // Values that closely follow Python and other lanuages
    | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | DEC_NUMBER // becomes INT at runtime
    | FLOAT_NUMBER                                      // becomes FLOAT at runtime
    | STRING
    | NAME -> var_ref

var_name: NAME ("." NAME)*

{EXTN_GRAMMAR}

{FUNCTIONS}

// modified versions of python.STRING/LONG_STRING : removed the [f]
// NB: we don't enforce validity of prefixes here
_VSTRING: /[BRUbru]*("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/
_LONG_VSTRING: /[BRUbru]*(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?''')/s
// Allow typographic quotes from C/P sources, but fix them up internally
_MS_STRING: /[BRUbru]*(\u201C.*?(?<!\\)(\\\\)*?\u201D|\u2018.*?(?<!\\)(\\\\)*?\u2019)/
STRING: _VSTRING | _LONG_VSTRING | _MS_STRING

SH_COMMENT: /#[^\n]*/
CPP_COMMENT: /\/\/[^\n]*/
C_COMMENT: "/*" /(.|\n)*?/ "*/"

%import common.WS
%ignore WS
%ignore SH_COMMENT
%ignore C_COMMENT
%ignore CPP_COMMENT
