#!/bin/bash

# A reduced version of mk-dist
#   * Only produces a whl
#   * If there are any "cygwin"-isms required, they go here

if [ ! -d "./src/vgr" ]; then
    echo "You are not in the project root" >&2
    exit 1
fi

PROJECT_ROOT=$(pwd)

OUTPUT_DIR="${PROJECT_ROOT}/dist"
# Ensure output directory exists and is empty
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

if [[ -z "${VIRTUAL_ENV:-}" ]]; then
    echo "Run: source scripts/dev-setup" >&2
    exit 1
fi

# Upgrade build tools
pip install --upgrade pip setuptools wheel build

# Build the wheel
python3 -m build

WHEEL_FILE=$(ls -t "$OUTPUT_DIR"/*.whl | head -n1)
echo "Created wheel \"$WHEEL_FILE\""

# Zip up the samples
SAMPLES_DIR="samples"
SAMPLES_ZIP="$OUTPUT_DIR/vgr-samples.zip"
echo "Building \"$SAMPLES_ZIP\"..."
cd "$SAMPLES_DIR"
zip -r "$SAMPLES_ZIP" ./*
cd - >/dev/null
