#! /usr/bin/env bash

if [ ! -d "./src/vgr" ]; then
    echo "You are not in the project root" >&2
    exit 1
fi

PROJECT_ROOT=$(pwd)

if [[ -z "${VIRTUAL_ENV:-}" ]]; then
    echo "Run: source scripts/dev-setup" >&2
    exit 1
fi

OUTPUT_DIR="${PROJECT_ROOT}/dist"
BUILD_DIR="${PROJECT_ROOT}/build"
# Ensure output directories exists and are empty
rm -rf "$OUTPUT_DIR" "$BUILD_DIR"
mkdir -p "$OUTPUT_DIR"

# Upgrade build tools
pip install --quiet --use-feature=in-tree-build --upgrade pip setuptools wheel build

# Build the wheel
python3 -m build --quiet --use-feature=in-tree-build --wheel --outdir "$OUTPUT_DIR"
rm -rf "$BUILD_DIR"

WHEEL_FILE=$(ls -t "$OUTPUT_DIR"/*.whl | head -n1)
VERSION=$(echo "$WHEEL_FILE" | sed -E 's@.+vgr-([0-9]+\.[0-9]+\.[0-9]+)-.+@\1@')

# Zip up the samples
SAMPLES_DIR="samples"
SAMPLES_ZIP="$OUTPUT_DIR/vgr-${VERSION}-samples.zip"
cd "$SAMPLES_DIR"
zip -q -r "$SAMPLES_ZIP" ./*
cd - >/dev/null

# Copy over the wheel installer script
cp "scripts/install-vgr" "$OUTPUT_DIR"
