#! /usr/bin/env bash

if [ ! -d "./src/vgr" ]; then
    echo "You are not in the project root" >&2
    exit 1
fi

python3 -m pip install --upgrade "pip>=23.0"
python3 -m pip install --quiet .[dev]

pytest -s --cov=vgr --cov-branch --cov-report=xml
