_TERMINAL: "Terminal"i

?term_statements: term_statement

term_statement: _TERMINAL _options_list{term_cmd}

?term_cmd: term_cursor_cmd
        |  term_opts_cmd
        |  term_edit_cmd
        |  term_misc_cmd
        |  term_scroll_cmd
        |  term_set_attr
        |  term_draw_box

term_cursor_cmd: "MoveCursorTo"i expr _CLAUSE_SEP expr     -> cup
        |        "GetCursorPos"i                           -> dsr_cursor
        |        "MoveCursorToLine"i expr?                 -> vpa
        |        "MoveCursorToCol"i expr?                  -> hpa
        |        "HomeCursor"i                             -> cup_home
        |        "SaveCursor"i                             -> decsc
        |        "RestoreCursor"i                          -> decrc
        |        "ShowCursor"i                             -> dectcem_set
        |        "HideCursor"i                             -> dectcem_reset
        |        "CursorVisible"i expr?                    -> dectcem
        |        "CursorUp"i expr?                         -> cuu
        |        "CursorDown"i expr?                       -> cud
        |        "CursorBack"i expr?                       -> cub
        |        "CursorForward"i expr?                    -> cuf

term_edit_cmd:   "InsertLine"i expr?                       -> il
        |        "DeleteLine"i expr?                       -> dl
        |        "InsertChar"i expr?                       -> ich
        |        "DeleteChar"i expr?                       -> dch
        |        "EraseChar"i expr?                        -> ech
        |        "EraseLine"i                              -> el
        |        "EraseEOL"i                               -> el_eol
        |        "EraseBOL"i                               -> el_bol
        |        "EraseDisplay"i                           -> ed    // Erase w/o cursor moving
        |        "EraseEOS"i                               -> ed_eos
        |        "EraseBOS"i                               -> ed_bos
        |        "ClearScreen"i                            -> clear // Erase + Home cursor

term_scroll_cmd: "ScrollUp"i                               -> ri
        |        "ScrollDown"i                             -> ind
        |        "ScrollRegion"i expr _CLAUSE_SEP expr     -> secstbm

term_opts_cmd:   "S7C1"i expr?                             -> s7c1t
        |        "S8C1"i expr?                             -> s8c1t
        |        "DECSCNM"i expr?                          -> decscnm
        |        "SmoothScroll"i expr?                     -> decsclm
        |        "OriginMode"i expr?                       -> decom
        |        "AutoWrap"i expr?                         -> decawm
        |        "InsertMode"i expr?                       -> irm

term_misc_cmd:   "PrintDHigh"i expr                        -> dh_print // double high printing
        |        "SetClipboard"i expr                      -> term_set_clipboard
        |        "SoftReset"i                              -> decstr
        |        "HardReset"i                              -> ris
        |        "AlignmentTest"i                          -> decaln
        |        "SetTab"i                                 -> hts
        |        "ClearTab"i                               -> tbc
        |        "ClearAllTabs"i                           -> tbc_all
        |        "RepeatChar"i expr?                       -> rep
        |        "DeIconify"i                              -> deiconify
        |        "RaiseWindow"i                            -> raise_window
        |        "SetIconName"i expr                       -> icon_name
        |        "SetTitle"i expr                          -> window_title
        |        ("GetTerminalSize"i | "GetTermSize"i)     -> term_size

term_set_attr:   "SetStyle"i expr                          -> sgr_style
        |        "SetForeground"i expr                     -> sgr_fg
        |        "SetBackground"i expr                     -> sgr_bg
        |        "ResetAttrs"i                             -> sgr_reset
        |        "BoldAttr"i expr?                         -> sgr_bold
        |        "DimAttr"i expr?                          -> sgr_dim
        |        "BlinkAttr"i expr?                        -> sgr_blink
        |        "ItalicsAttr"i expr?                      -> sgr_italic
        |        "UnderlineAttr"i expr?                    -> sgr_underline
        |        "ReverseAttr"i expr?                      -> sgr_reverse
        |        "HiddenAttr"i expr?                       -> sgr_hidden
        |        "StrikethruAttr"i expr?                   -> sgr_strikethru
        |        "DoubleWide"i expr?                       -> decdwl
        |        "SingleWide"i expr?                       -> decswl
        |        "DHighTop"i expr?                         -> decdhl_top
        |        "DHighBottom"i expr?                      -> decdhl_bot

term_draw_box:   "DrawBox"i expr _CLAUSE_SEP expr (_CLAUSE_SEP expr)? -> box
        |        "DrawHLine"i expr (_CLAUSE_SEP expr)?                -> hline
        |        "DrawVLine"i expr (_CLAUSE_SEP expr)?                -> vline
