?ldap_statements: ldap_connect
    | ldap_disconnect
    | ldap_search

// Connections
ldap_connect   : "Ldap"i "Connect"i (_COMMA? ldap_conn_arg)* _SEMICOLON?
ldap_disconnect: "Ldap"i "Disconnect"i ("From"i? expr)? _SEMICOLON?

ldap_conn_arg: ("To"i | "URL"i "Is"i?) expr -> lopt_url                                      // string
    | "User"i "Is"i? expr -> lopt_user                                                       // string
    | "Password"i "Is"i? expr -> lopt_password                                               // string
    | ("Authentication"i | "Auth"i) "Is"i? expr -> lopt_authentication                       // constrained string
    | ("Read"i "Only"i | "Read-Only"i) ("Is"i? expr)? -> lopt_read_only                      // bool
    | "Time"i "Limit"i "Is"i? expr -> lopt_time_limit                                        // int, seconds
    | "Page"i "Size"i "Is"i? expr -> lopt_paged_size                                         // int
    | "Return"i? "Empty"i ("Attributes"i | "Attrs"i) ("Is"i? expr)? -> lopt_return_empty_attributes // bool
    | "As"i expr -> lopt_conn_name                                                           // string

// Searching
ldap_search: "Ldap"i "Search"i (_COMMA? ldap_search_option (_COMMA? ldap_search_option)*)? _SEMICOLON?

?ldap_search_option: "Base"i "Is"i? expr -> lopt_search_base                                 // string
    | "Filter"i "Is"i? expr -> lopt_search_filter                                            // string
    | "Scope"i "Is"i? expr -> lopt_search_scope                                              // constrained string
    | ("Attributes"i | "Attrs"i) ("Is"i | "Are"i)? expr -> lopt_attributes                   // list of string
    | "Dereference"i "Aliases"i ("Is"i? expr)? -> lopt_dereference_aliases                   // bool
    | "Get"i "Operational"i ("Attributes"i | "Attrs"i) ("Is"i? expr)? -> lopt_get_operational_attributes  // bool
    | "Time"i "Limit"i "Is"i? expr -> lopt_time_limit                                        // int, seconds
    | "Size"i "Limit"i "Is"i? expr -> lopt_size_limit                                        // int
    | "Giving"i var_name -> lopt_giving                                                      // variable path
    | "Using"i "Connection"i? expr -> lopt_using                                             // string
