
?cobol_statements: cobol_accept
    | cobol_add_giving
    | cobol_add_to
    | cobol_display_on
    | cobol_div_by
    | cobol_div_into
    | cobol_evaluate
    | cobol_exit
    | cobol_exhibit
    | cobol_move_to
    | cobol_mul_by
    | cobol_perform_times
    | cobol_perform_until
    | cobol_perform_varying
    | cobol_string
    | cobol_sub_from
    | cobol_sub_giving

_cob_expr_list: expr (_SEP? expr)*
_cob_var_list: var_name (_SEP? var_name)*

// DATE and TIME should accept either a keyword -or- a pattern
cobol_accept: "Accept"i var_name "Upon"i "Console"i cobol_accept_option? -> cobol_accept_input // old standard
    | "Accept"i var_name ("From"i ("Console"i | "Terminal"i | "Stdin"i | "Sysin"i | "Sysinp"i))? cobol_accept_option? -> cobol_accept_input
    | "Accept"i var_name "From"i "Date"i -> cobol_accept_date
    | "Accept"i var_name "From"i "Date"i "YYYYMMDD"i -> cobol_accept_yyyymmdd
    | "Accept"i var_name "From"i "Day"i -> cobol_accept_day
    | "Accept"i var_name "From"i "Day"i "YYYYDDD"i -> cobol_accept_yyyyddd
    | "Accept"i var_name "From"i "Day-Of-Week"i -> cobol_accept_dow
    | "Accept"i var_name "From"i "Time"i -> cobol_accept_time
    | "Accept"i var_name "From"i ("Unix"i? "Epoch"i | "Timestamp"i) -> cobol_accept_epoch
cobol_accept_option: "With"i? "Echo"i -> echo // AcuCobol (plus a "with")
    | "With"i? "No"i "Echo"i -> no_echo // Micro Focus, AcuCobol, and GnuCobol
    | "No-Echo"i -> no_echo // Micro Focus and GnuCobol
    | "Secure"i -> secure // Micro Focus and GnuCobol

cobol_exit: "Exit"i "Perform"i "Cycle"i -> cobol_exit_perform_cycle
    | "Exit"i "Perform"i -> cobol_exit_perform
    | ("Exit"i "Program"i | "Goback"i) -> cobol_exit_program

// NB: Performs contain non-standard ":" separator (optional) to be compatible with other block statements
cobol_perform_times: "Perform"i expr ("Time"i | "Times"i) _CLAUSE_SEP? statement+ ("End-Perform"i | "End"i)?
cobol_perform_until: "Perform"i "Until"i expr _CLAUSE_SEP? statement+ ("End-Perform"i | "End"i)?
cobol_perform_varying: "Perform"i varying_test_type? "Varying"i var_name "From"i expr "By"i expr "Until"i expr _CLAUSE_SEP? statement+ ("End-Perform"i | "End"i)?
?varying_test_type: "With"i? "Test"i "Before"i -> test_before
    | "With"i? "Test"i "After"i -> test_after

cobol_exhibit: "Exhibit"i "*" // exhibit all
    | "Exhibit"i _cob_var_list

// Notes :
//  * We do not enforce the order (or cardinality) of options
//  * Output limits based on the destination are not enforced
//
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-display-statement
cobol_display_on: "Display"i _cob_expr_list cobol_display_opt*
?cobol_display_opt: ("Upon"i | "On"i) (stderr | stdout | stdin) -> upon
    | "With"i? "No"i "Advancing"i -> no_advance

// Notes :
//   * Does not support "[Not] On Size Error" (entirely N/A here)
//   * Does not support "Pointer"
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-string-statement
cobol_string: "String"i _options_list{cobol_string_source} _SEP? "Into"i var_name "End-String"i?
?cobol_string_source: expr ("Delimited"i "By"i "Size"i)? -> full
    | expr "Delimited"i "By"i expr -> delimited

cobol_add_to: "Add"i _cob_expr_list "To"i var_name "End-Add"i?
cobol_add_giving: "Add"i _cob_expr_list "To"i expr "Giving"i var_name "End-Add"i?

cobol_sub_from: "Subtract"i _cob_expr_list "From"i var_name "End-Subtract"i?
cobol_sub_giving: "Subtract"i _cob_expr_list "From"i expr "Giving"i var_name "End-Subtract"i?

// Notes:
//   * Only one var_name can be specified
//   * Accepts but ignores "rounded"
//   * Does not support "[Not] On Size Error" (entirely N/A here)
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-multiply-statement
cobol_mul_by: "Multiply"i expr "By"i (expr "Giving"i)? var_name "Rounded"i? "End-Multiply"i?

// Notes :
//   * Does not support multiple receivers
//   * Accepts but ignores "rounded"
//   * Does not support "remainder"
//   * Does not support "[Not] On Size Error" (entirely N/A here)
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-divide-statement
cobol_div_into: "Divide"i expr "Into"i (expr "Giving"i)? var_name "Rounded"i? "End-Divide"i?
cobol_div_by: "Divide"i expr "By"i expr "Giving"i var_name "Rounded"i? "End-Divide"i?

cobol_move_to: "Move"i cobol_move_corr? expr "To"i var_name
cobol_move_corr: ("Corresponding"i | "Corr"i)

// Notes :
//   * Does not support "Also"
//   * Muliple (fall-thru) "When" blocks not supported
//   * "Any" is not supported
// NB: Evaluate contain non-standard ":" separator (optional) to be compatible with other block statements
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-evaluate-statement
cobol_evaluate: "Evaluate"i expr _CLAUSE_SEP? (cobol_when_block | cobol_when_thru_block)+ cobol_when_other? "End-Evaluate"i -> cobol_evaluate
cobol_when_thru_block: "When"i expr ("Through"i | "Thru"i) expr _CLAUSE_SEP? statement+
    | "When"i "Not"i expr ("Through"i | "Thru"i) expr _CLAUSE_SEP? statement+ -> cobol_when_not_thru_block
cobol_when_block: "When"i expr _CLAUSE_SEP? statement+
    | "When"i "Not"i expr _CLAUSE_SEP? statement+ -> cobol_when_not_block
cobol_when_other: "When"i "Other"i _CLAUSE_SEP? statement+
