
?cobol_statements: cobol_exit_perform
    | cobol_exhibit
    | cobol_move_to
    | cobol_perform_varying
    | cobol_string

_cob_expr_list: expr (_SEP? expr)*
_cob_var_list: var_name (_SEP? var_name)*

cobol_exit_perform: "Exit"i "Perform"i

// NB: Performs contain non-standard ":" separator (optional) to be compatible with other block statements
cobol_perform_varying: "Perform"i varying_test_type? "Varying"i var_name "From"i expr "By"i expr "Until"i expr _CLAUSE_SEP? statement+ ("End-Perform"i | "End"i)?
?varying_test_type: "With"i? "Test"i "Before"i -> test_before
    | "With"i? "Test"i "After"i -> test_after

cobol_exhibit: "Exhibit"i "*" // exhibit all
    | "Exhibit"i _cob_var_list

// Notes :
//   * Does not support "[Not] On Size Error" (entirely N/A here)
//   * Does not support "Pointer"
// See https://www.ibm.com/docs/en/cobol-zos/6.3.0?topic=statements-string-statement
cobol_string: "String"i _options_list{cobol_string_source} _SEP? "Into"i var_name "End-String"i?
?cobol_string_source: expr ("Delimited"i "By"i "Size"i)? -> full
    | expr "Delimited"i "By"i expr -> delimited

cobol_move_to: "Move"i cobol_move_corr? expr "To"i var_name
cobol_move_corr: ("Corresponding"i | "Corr"i)
