name: Build Tester

on:
  workflow_dispatch:
  schedule:
    - cron: '47 7 * * 2,4,6'
  push:
    paths:
      - "pyproject.toml"
      - "scripts/build"
      - ".github/workflows/build-tester.yml"

jobs:
  test-build-release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.9'
      - run:  python -m pip install ".[dev]"
      - run:  ./scripts/build "${GITHUB_REF_NAME}"
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 14
