name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-and-build:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.9'   # 3.9.6 used on macOS 14.6.1 used in dev
      - run: pip install -r requirements-dev.txt
      - name:  Test
        run:   ./scripts/test
      - name:  Build
        run:   ./scripts/build
  release:
    needs: test-and-build
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: false
          name: ${{ github.ref_name }}
          body_path: ./dist/vgr-${{ env.VERSION }}-RELEASE-NOTES.md
          files: ./dist/*
